# One spec per SKU, read off its figure in the Technical Annex v3 (sheet number in `sheet`).
# Blocks are (key, title, subtitle[, column span]). Edges are (from, to, marker, colour).
# Where the figure and the compendium chapter the product page is written from disagree, the drawing
# follows the product page; `differs` states each difference, sheet value against page value;
# it appears beside the annex link on the page and in the guide. Certification wording on a figure is not drawn; `toward` repeats the product page.

TI_FOC = {'title': 'Field Orientated Control of 3-Phase AC-Motors (TI BPRA073)', 'note': 'The Clarke and Park transforms, the PI regulator and PWM behind the control datapath.', 'href': 'https://www.ti.com/lit/an/bpra073/bpra073.pdf', 'meta': 'Texas Instruments · PDF'}
CORDIC = {'title': 'The CORDIC trigonometric computing technique', 'note': 'Volder, IRE Transactions on Electronic Computers, 1959: the shift-and-add method behind the CORDIC block.', 'href': 'https://doi.org/10.1109/TEC.1959.5222693', 'meta': 'IEEE · DOI'}
RISCV = {'title': 'RISC-V ratified specifications', 'note': 'The instruction set the DGridRiscV cores execute.', 'href': 'https://riscv.org/specifications/ratified/', 'meta': 'RISC-V International'}
AMBA = {'title': 'Arm AMBA specifications, including AXI and AHB', 'note': 'The bus protocol family the on-chip bus is modelled on.', 'href': 'https://www.arm.com/architecture/system-architectures/amba/amba-specifications', 'meta': 'Arm'}
BROKAW = {'title': 'A simple three-terminal IC bandgap reference', 'note': 'Brokaw, IEEE Journal of Solid-State Circuits, 1974: the bandgap cell the reference is built on.', 'href': 'https://doi.org/10.1109/JSSC.1974.1050532', 'meta': 'IEEE · DOI'}
HERCULES = {'title': 'Hercules safety MCUs (TI SPRY178)', 'note': 'Lockstep CPUs with a cycle offset, and why a watchdog should be windowed.', 'href': 'https://www.ti.com/lit/fs/spry178/spry178.pdf', 'meta': 'Texas Instruments · PDF'}
CAN = {'title': 'Introduction to the Controller Area Network (TI SLOA101)', 'note': 'CAN arbitration, bit timing and the physical layer of ISO 11898-2.', 'href': 'https://www.ti.com/lit/an/sloa101b/sloa101b.pdf', 'meta': 'Texas Instruments · PDF'}

SPECS = [
 {'id': 'sku1', 'slug': 'sku-1', 'code': 'SKU-1', 'sheet': '2', 'name': 'BLDC motor controller',
  'title': 'SKU-1 BLDC motor controller system architecture',
  'subtitle': 'Host control plane, mixed signal and power path on one AXI bus; a hardware field-oriented-control datapath closes the current loop · from Technical Annex v3, sheet 2',
  'frame': 'SKU-1  ·  130 nm BCD / high-voltage CMOS  ·  100 MHz',
  'input': 'Speed (rpm) · torque · halt · brake · ramp up / down   (host commands)',
  'about': 'SKU-1 is a brushless-motor controller that keeps the current loop in hardware. A DGridRiscV core configures and supervises; the field-oriented-control datapath, the 16-bit sensing and the PWM and pre-drivers run the loop without it, controlling a 5 V to 120 V motor supply (external power switches above 20 V).',
  'rows': [
   {'h': 250, 'zones': [
     {'key': 'Z1', 'name': 'Host · control plane', 'color': 'blue', 'cols': 2, 'w': 1.1,
      'what': 'A DGridRiscV core with timers and watchdog, SRAM and ReRAM, and the host interfaces. It sets the loop up and supervises it.',
      'why': 'The processor configures and supervises; it does not sit in the loop.',
      'blocks': [('CPU', 'DGridRiscV', 'custom 32-bit RISC-V · 100 MHz'), ('TMR', 'Timers · WDT · CCU', ''), ('SRAM', 'SRAM', '32 KB, up to 256 KB'), ('RERAM', 'ReRAM', '256 KB, up to 1 MB'), ('IO', 'Host interfaces', 'I²C slave · UART × 4 · SPI · CAN-FD × 2 · JTAG', 2)]},
     {'key': 'Z2', 'name': 'Mixed signal', 'color': 'amber', 'cols': 2, 'w': 0.8,
      'what': 'A 16-bit ADC for phase, bus and temperature, four reference DACs, an on-die temperature sensor and three current-sense amplifiers.',
      'blocks': [('ADC', '16-bit ADC', 'phase / bus / temp'), ('DAC', 'DAC × 4', 'reference out'), ('TEMP', 'Temp sense', 'on-die, −40 to +125 °C'), ('CSA', 'CSA × 3', 'current-sense amps')]},
     {'key': 'Z3', 'name': 'Power path', 'color': 'red', 'cols': 3, 'w': 1.3,
      'what': 'A buck-boost converter, seven PWM channels, three half-bridge pre-drivers, latched protection and runtime star or delta winding selection.',
      'why': 'Up to about 20 V the gate drive sits on the BCD die beside the logic; above it, up to 120 V, the chip drives external power switches.',
      'blocks': [('BB', 'B-B converter', 'buck-boost, PWM-pin driven'), ('PWM', 'PWM × 7', 'up to 200 kHz · 6 bridge + 1 aux'), ('PRE', 'Pre-drivers R / Y / B', '3 half-bridges · clock gating per phase'), ('SD', 'Star / delta', 'winding configuration, runtime selectable'), ('PROT', 'Protection', 'thermal · overcurrent · overvoltage → gate shutdown, latched'), None]},
   ]},
   {'bus': 'AXI bus  ·  memory-mapped register file  ·  100 MHz'},
   {'h': 170, 'zones': [
     {'key': 'Z4', 'name': 'Field-oriented control datapath', 'color': 'purple', 'cols': 4, 'w': 1.6,
      'what': 'A hardware PID tuner, a CORDIC rectangular-to-polar stage, inverse Park and Clarke, and sine or trapezoid lookup: torque command in, phase drive out.',
      'why': 'The loop runs in hardware, so its latency is fixed and stays under 1 µs.',
      'blocks': [('PID', 'PID tuner', 'hardware · <1 µs tuning latency'), ('RP', 'Rect → polar', 'CORDIC · magnitude + angle'), ('DQ', 'd,q → 3-phase', 'inverse Park + Clarke'), ('SINE', 'Sine / trapezoid', 'lookup tables · sinusoidal or 6-step')]},
     {'key': 'Z5', 'name': 'Sensor + feedback', 'color': 'green', 'cols': 2, 'w': 1,
      'what': 'Hall, quadrature or encoder inputs give rotor angle and speed; the three phase currents are rebuilt, amplified and digitised.',
      'blocks': [('HALL', 'Hall / quad / enc', 'sensored or sensorless'), ('ANG', 'Angle (ω)', 'rotor position + speed'), ('REB', 'iR iY iB rebuild', 'transfer function'), ('CUR', 'Instant current', 'amplify + digitise')]},
   ]},
  ],
  'strip': ('Artix-7 FPGA · 81.25 MHz · validation only', '130 nm ASIC · SkyWater SKY130 / IHP SG13G2 open PDK · 100 MHz fixed'),
  'edges': [('IN', 'Z1', '①', 'blue', 'exitX=0.5;exitY=1;entryX=0.62;entryY=0;'), ('PID', 'RP', '②', 'purple'), ('RP', 'DQ', '', 'purple'), ('DQ', 'SINE', '', 'purple'), ('Z4', 'Z3', '', 'purple', 'exitX=0.92;exitY=0;entryX=0.1;entryY=1;'),
            ('BB', 'PWM', '', 'amber'), ('PWM', 'PRE', '③', 'red'), ('Z5', 'Z4', '④', 'green', 'exitX=0;exitY=0.85;entryX=1;entryY=0.85;'), ('PROT', 'PRE', 'F', 'red', 'exitX=1;exitY=0.5;entryX=0.5;entryY=1;')],
  'markers': [('①', 'Speed, torque, halt and brake commands reach the host.'), ('②', 'The datapath turns the torque command into phase drive: PID, CORDIC, inverse Park and Clarke, waveform lookup.'),
              ('③', 'PWM drives the three half-bridge pre-drivers.'), ('④', 'Current and angle feedback closes the PID loop.'), ('F', 'A thermal, overcurrent or overvoltage fault shuts the gates and latches.')],
  'toward': ['AEC-Q100 Grade 0', 'ISO 26262 ASIL-B/C', 'UL94'],
  'alt': 'SKU-1 BLDC motor controller architecture diagram: host control plane, mixed signal and power path on an AXI bus, the field-oriented-control datapath and the sensor feedback that closes the PID loop',
  'caption': 'Redrawn from the Technical Annex v3, sheet 2. Numbered markers trace the control loop; F marks the latched protection trip. Values are design targets.',
  'background': [TI_FOC, CORDIC, RISCV, AMBA]},

 {'id': 'sku2', 'slug': 'sku-2', 'code': 'SKU-2', 'sheet': '3', 'name': 'smart-meter SoC',
  'title': 'SKU-2 smart-meter SoC system architecture',
  'subtitle': 'Six-channel metrology, compute and security, and an always-on domain on a 32-bit AHB-Lite multilayer bus · from Technical Annex v3, sheet 3',
  'frame': 'SKU-2  ·  130 nm CMOS  ·  100 MHz',
  'input': 'V / I sense · 6 channels',
  'about': 'SKU-2 is an energy-meter SoC. Six sigma-delta channels feed a decimator and a metrology engine that computes real, reactive and apparent power and harmonics; a DGridRiscV core, a security engine and an always-on domain handle billing, tamper and timekeeping.',
  'rows': [
   {'h': 170, 'zones': [
     {'key': 'Z1', 'name': 'Metrology', 'color': 'green', 'cols': 3, 'w': 1.4,
      'what': 'A six-channel 24-bit sigma-delta front end, a sinc³ decimator at OSR 256, and a metrology engine for P, Q, S and THD to the 15th harmonic.',
      'why': 'Billing accuracy is set by the converter and the arithmetic, so both are dedicated hardware.',
      'blocks': [('AFE', 'DG-AFE6', '6-ch 24-bit delta-sigma'), ('DEC', 'DECIM', 'sinc³ · OSR 256'), ('MET', 'METRO', 'P Q S · THD-15')]},
     {'key': 'Z2', 'name': 'Compute + security', 'color': 'blue', 'cols': 3, 'w': 1.4,
      'what': 'A DGridRiscV core, a four-channel DMA and the DG-SE security engine with AES-256 and SHA-256.',
      'blocks': [('CPU', 'DGridRiscV', 'RV32IM_Zicsr'), ('DMA', 'DMA', '4-ch'), ('SE', 'DG-SE', 'AES-256 · SHA-256')]},
     {'key': 'Z3', 'name': 'Always-on', 'color': 'amber', 'cols': 1, 'w': 0.7,
      'what': 'A PMU and RTC on a 32.768 kHz crystal with brownout detection, drawing under 2 µW.',
      'why': 'Time and tamper state must survive when mains power is gone.',
      'blocks': [('PMU', 'PMU + RTC', '32.768 kHz XTAL · brownout 2.0 V · <2 µW')]},
   ]},
   {'bus': 'AHB-Lite multilayer  ·  32-bit  ·  4 masters / 9 slaves  ·  100 MHz'},
   {'h': 120, 'zones': [
     {'key': 'Z4', 'name': 'Peripherals', 'color': 'grey', 'cols': 6, 'w': 1,
      'what': 'Tamper-logging RTC, capture and compare timer, 4 × 40 segment LCD, DLMS/COSEM UART, case and magnet tamper inputs, and GPIO for relay and LED.',
      'blocks': [('RTC', 'RTC', 'tamper log'), ('TIM', 'Timer', 'capture / compare'), ('LCD', 'LCD', '4 × 40 seg'), ('UART', 'UART', 'DLMS / COSEM'), ('TAMP', 'Tamper', 'case · magnet'), ('GPIO', 'GPIO', 'relay + LED')]},
   ]},
  ],
  'edges': [('IN', 'AFE', '①', 'green'), ('AFE', 'DEC', '②', 'green'), ('DEC', 'MET', '③', 'green'), ('MET', 'BUS', '④', 'blue'), ('BUS', 'UART', '⑤', 'main')],
  'markers': [('①', 'Six voltage and current channels enter the front end.'), ('②', 'The 24-bit samples decimate through sinc³ at OSR 256.'), ('③', 'The metrology engine computes P, Q, S and THD.'),
              ('④', 'Results cross the 32-bit bus to the core and DMA.'), ('⑤', 'Readings leave on the DLMS/COSEM UART.')],
  'toward': ['IEC metering accuracy Class 0.5S'],
  'alt': 'SKU-2 smart-meter SoC architecture diagram: six-channel metrology, compute and security, and an always-on PMU and RTC on an AHB-Lite bus, with six peripherals below',
  'caption': 'Redrawn from the Technical Annex v3, sheet 3. Numbered markers trace one measurement from the sense inputs to the meter UART. Values are design targets.',
  'background': [{'title': 'DLMS User Association', 'note': 'The DLMS/COSEM metering protocol the UART speaks.', 'href': 'https://www.dlms.com/', 'meta': 'DLMS UA'}, RISCV, AMBA]},

 {'id': 'sku3', 'slug': 'sku-3', 'code': 'SKU-3', 'sheet': '4', 'name': 'hi-rel power-management IC',
  'title': 'SKU-3 hi-rel PMIC system architecture',
  'subtitle': 'Input conditioning, a peak-current-mode pre-regulator, four monitored rails and an upset-hardened sequencer for a 28 V aircraft bus · from Technical Annex v3, sheet 4',
  'frame': 'SKU-3  ·  180 nm BCD production, 130 nm 20 V devices for prototyping',
  'input': '28 V aircraft bus',
  'differs': 'the rails (the sheet draws 3V3 and 1V8 LDOs at 2 A and 3 A and 1V2 and 0V9 bucks at 5 A and 6 A; this page states 5 V and 3.3 V bucks at 2 A and 3 A and 1.8 V and 1.2 or 0.9 V LDOs at 500 mA and 300 mA), the telemetry ADC (12-bit on the sheet, 10-bit at 500 kSPS here) and the sequencer (8 slots on the sheet, 4 steps here)', 'about': 'SKU-3 turns a 28 V aircraft or vehicle bus into four sequenced, monitored rails. It conditions the input, pre-regulates with a synchronous buck under peak-current-mode control, and supervises every rail with window monitors, current limits and an upset-hardened sequencer.',
  'rows': [
   {'h': 230, 'zones': [
     {'key': 'Z1', 'name': 'Input conditioning', 'color': 'green', 'cols': 2, 'w': 1,
      'what': 'EMI filter and TVS clamp, an ideal-diode reverse-polarity stage, soft-start inrush limiting, and hysteretic under- and over-voltage lockout.',
      'why': 'An aircraft bus carries surges and spikes the downstream rails must never see.',
      'blocks': [('EMI', 'EMI + TVS', 'CM choke + pi · clamp 36 V'), ('DIODE', 'Ideal diode', 'reverse polarity · back-to-back LDMOS'), ('INR', 'Inrush', 'soft-start FET · dI/dt limited'), ('UV', 'UVLO + OVLO', '18 V / 34 V · hysteretic')]},
     {'key': 'Z2', 'name': 'Pre-regulator · synchronous buck', 'color': 'red', 'cols': 3, 'w': 1.5,
      'what': 'A type-III error amplifier, a PWM comparator with slope compensation, an adaptive dead-time gate driver, an LDMOS half-bridge power stage and sense-FET current sensing.',
      'why': 'Peak-current-mode control limits current cycle by cycle, so a fault downstream cannot run away.',
      'blocks': [('EA', 'Error amp', 'type-III comp · 60 dB DC'), ('PC', 'PWM comp', '+ slope comp · 500 kHz to 2 MHz'), ('GD', 'Gate driver', 'adaptive dead-time · 20 ns non-overlap'), ('CS', 'Current sense', 'sense-FET + amp · cycle-by-cycle limit'), ('PS', 'Power stage', 'LDMOS half-bridge', 2)]},
     {'key': 'Z3', 'name': 'Reference + bias', 'color': 'amber', 'cols': 2, 'w': 1,
      'what': 'A Brokaw bandgap at 1.20 V and 12 ppm/°C with one-time OTP trim, PTAT and CTAT bias, and an 8 MHz RC oscillator.',
      'blocks': [('BG', 'Bandgap', 'Brokaw cell · 1.20 V · 12 ppm/°C'), ('TRIM', 'Trim', 'OTP 6-bit · one-time, post-package'), ('BIAS', 'Bias', 'PTAT + CTAT'), ('OSC', 'Osc', 'RC 8 MHz · ±2% trimmed')]},
   ]},
   {'h': 330, 'zones': [
     {'key': 'Z4', 'name': 'Rail generation', 'color': 'blue', 'cols': 3, 'mcols': 3, 'w': 2.2,
      'what': 'Four sequenced rails, two bucks at 5 V and 3.3 V and two LDOs at 1.8 V and 1.2 or 0.9 V, each followed by an over- and under-voltage window monitor and a foldback current limit that reports power-good.',
      'blocks': [('R1', 'Buck · 5 V', '2 A · soft-start ramp'), ('W1', 'Window monitor', 'OV / UV · ±3% window'), ('O1', 'OC limit', 'foldback → PG'),
                 ('R2', 'Buck · 3.3 V', '3 A · soft-start ramp'), ('W2', 'Window monitor', 'OV / UV · ±3% window'), ('O2', 'OC limit', 'foldback → PG'),
                 ('R3', 'LDO · 1.8 V', '500 mA · soft-start ramp'), ('W3', 'Window monitor', 'OV / UV · ±3% window'), ('O3', 'OC limit', 'foldback → PG'),
                 ('R4', 'LDO · 1.2 / 0.9 V', '300 mA · soft-start ramp'), ('W4', 'Window monitor', 'OV / UV · ±3% window'), ('O4', 'OC limit', 'foldback → PG')]},
     {'key': 'Z5', 'name': 'Supervision · sequencing · telemetry', 'color': 'purple', 'cols': 2, 'w': 1,
      'what': 'A programmable four-step sequencer, a 10-bit 500 kSPS telemetry ADC for voltage, current and die temperature over SPI, a windowed watchdog, and DICE latches with TMR on the sequencer state machine.',
      'why': 'A single-event upset must not reorder or drop a rail, so the sequencer state is hardened by design.',
      'blocks': [('SEQ', 'Sequencer', 'programmable 4-step order · FSM + delay counter · TMR'), ('TEL', 'Telemetry', '10-bit SAR ADC · 500 kSPS · V / I / die temp · SPI'), ('WDG', 'Watchdog', 'windowed · 1 ms / 10 ms'), ('SEU', 'SEU harden', 'DICE latches · TMR on the FSM')]},
   ]},
  ],
  'edges': [('IN', 'Z1', '①', 'green', 'exitX=0.5;exitY=1;entryX=0.65;entryY=0;'), ('EMI', 'INR', '', 'green'), ('INR', 'UV', '', 'green'), ('Z1', 'Z2', '②', 'red', 'exitX=1;exitY=0.75;entryX=0;entryY=0.75;'), ('EA', 'PC', '', 'red'), ('PC', 'GD', '', 'red'), ('Z2', 'Z4', '③', 'red', 'exitX=0.5;exitY=1;entryX=0.62;entryY=0;'), ('R1', 'W1', '', 'blue'), ('W1', 'O1', '', 'blue'), ('O1', 'SEQ', '④', 'amber'), ('CS', 'EA', '⑤', 'amber')],
  'markers': [('①', 'The 28 V bus enters input conditioning.'), ('②', 'The conditioned bus feeds the pre-regulator.'), ('③', 'The pre-regulator output feeds the four rail regulators.'),
              ('④', 'Each rail reports power-good to the sequencer through its window monitor and current limit.'), ('⑤', 'Current sense closes the peak-current-mode inner loop.')],
  'toward': ['DO-160 sections 16 and 17', 'MIL-STD-704F', 'MIL-STD-1275D', 'MIL-STD-461G', 'MIL-STD-883 Class B'],
  'alt': 'SKU-3 hi-rel PMIC architecture diagram: input conditioning, a synchronous-buck pre-regulator, reference and bias, four monitored rails, and supervision, sequencing and telemetry',
  'caption': 'Redrawn from the Technical Annex v3, sheet 4, with rail values from the product specification. Numbered markers trace power from the 28 V bus to the rails and the sequencer.',
  'background': [BROKAW, {'title': 'Upset hardened memory design for submicron CMOS technology', 'note': 'Calin, Nicolaidis and Velazco, IEEE Transactions on Nuclear Science, 1996: the DICE latch.', 'href': 'https://doi.org/10.1109/23.556880', 'meta': 'IEEE · DOI'},
                 {'title': 'Compensating the current-mode-controlled boost (TI SLVA452)', 'note': 'Slope compensation and type-II/III loop compensation for peak-current-mode converters.', 'href': 'https://www.ti.com/lit/an/slva452/slva452.pdf', 'meta': 'Texas Instruments · PDF'}]},

 {'id': 'sku5', 'slug': 'sku-5', 'code': 'SKU-5', 'sheet': '6', 'name': 'interface transceiver',
  'title': 'SKU-5 interface transceiver system architecture',
  'subtitle': 'Two line drivers on one die, an RS-485 channel and a CAN-FD channel, each with its own logic interface, protection, supply and clock · from Technical Annex v3, sheet 6',
  'frame': 'SKU-5  ·  130 nm with 5 V thick-oxide LDMOS',
  'about': 'SKU-5 is a line transceiver with one RS-485 channel and one CAN-FD channel. Each channel shifts 1.8 V logic to a 5 V thick-oxide output stage, shapes its edges, biases the bus to a defined idle state, and protects itself against shorts, heat and ESD.',
  'note': 'Bus figures follow the product page: the annex sheet’s “±7 V” common mode and “IEC 61000-4-2 ±15 kV HBM” are drawn in their corrected forms.',
  'rows': [
   {'h': 470, 'zones': [
     {'key': 'Z1', 'name': 'Channel 1 · RS-485  ·  half duplex · up to 256 nodes · −7 to +12 V CM', 'color': 'blue', 'cols': 3, 'w': 1,
      'what': 'Logic interface with TXD, RXD and enable, a slew-shaped pre-driver, a differential push-pull output on thick-oxide LDMOS, a 30 mV-hysteresis receiver, failsafe idle bias, fault and ESD protection, a local LDO and an oscillator.',
      'why': 'A 5 V-tolerant thick-oxide ring is why 130 nm suits a line driver.',
      'blocks': [('L1', 'Logic IF', '1.8 V core · level shift to 5 V · TXD · RXD · EN/STB'), ('P1', 'Pre-driver', 'slew shaping · dV/dt 3 V/ns trimmed'), ('O1', 'Output stage', 'diff push-pull · thick-oxide 5 V LDMOS'),
                 ('G1', 'Prot logic', 'EN interlock · no bus contention'), ('FT1', 'Fault', 'thermal + short · 150 °C shutdown'), ('R1', 'Receiver', 'hysteresis comp · 30 mV hyst · 50 ns prop'),
                 ('F1', 'Failsafe bias', 'idle = recessive · open / short / idle'), ('E1', 'ESD + EMC', '±15 kV, rated per test standard'), ('S1', 'Local supply + osc', '3.3 V LDO + bandgap · 40 MHz ref')]},
     {'key': 'PINS', 'name': 'Bus pins', 'color': 'grey', 'cols': 1, 'w': 0.28,
      'what': 'RS-485 A and B, CAN CANH and CANL.',
      'blocks': [('AB', 'A / B', 'RS-485'), ('CANP', 'CANH / CANL', 'CAN-FD')]},
     {'key': 'Z2', 'name': 'Channel 2 · CAN-FD  ·  8 Mbps data · ISO 11898-2 · ±12 V CM', 'color': 'green', 'cols': 3, 'w': 1,
      'what': 'The same structure for CAN-FD: logic interface, pre-driver, output stage, receiver, failsafe bias, fault and ESD protection, with a TXD timeout and bus-fault detection, and an oscillator for bit-time recovery.',
      'blocks': [('S2', 'Local supply + osc', '3.3 V LDO + bandgap · 40 MHz · bit-time recovery'), ('E2', 'ESD + EMC', '±15 kV, rated per test standard'), ('F2', 'Failsafe bias', 'idle = recessive · open / short / idle'),
                 ('O2', 'Output stage', 'diff push-pull · thick-oxide 5 V LDMOS'), ('P2', 'Pre-driver', 'slew shaping · dV/dt 3 V/ns trimmed'), ('L2', 'Logic IF', '1.8 V core · level shift to 5 V · TXD · RXD · EN/STB'),
                 ('R2', 'Receiver', 'hysteresis comp · 30 mV hyst · 50 ns prop'), ('FT2', 'Fault', 'thermal + short · 150 °C shutdown'), ('G2', 'Prot logic', 'TXD timeout · bus-fault detect')]},
   ]},
  ],
  'edges': [('L1', 'P1', '①', 'main'), ('P1', 'O1', '②', 'amber'), ('O1', 'AB', '③', 'red'), ('AB', 'R1', '④', 'blue'), ('L2', 'P2', '', 'main'), ('P2', 'O2', '', 'amber'), ('O2', 'CANP', '', 'red'), ('CANP', 'R2', '', 'blue')],
  'markers': [('①', 'TXD enters the logic interface and is level-shifted to 5 V.'), ('②', 'The pre-driver shapes the edge for the output stage.'), ('③', 'The differential output drives the bus pins.'), ('④', 'The receiver reads the bus back to RXD. Channel 2 follows the same path.')],
  'toward': ['TIA/EIA-485', 'ISO 11898-2', 'IEC 61000-4-2 (system level) and HBM (component level), each rated separately'],
  'alt': 'SKU-5 interface transceiver architecture diagram: an RS-485 channel and a CAN-FD channel, each with logic interface, pre-driver, output stage, receiver, failsafe bias, fault and ESD protection, sharing the bus-pin column',
  'caption': 'Redrawn from the Technical Annex v3, sheet 6. Numbered markers trace one transmit and receive on channel 1; channel 2 is the same. Bus figures use the corrected forms stated on this page.',
  'background': [{'title': 'The RS-485 Design Guide (TI SLLA272)', 'note': 'Common-mode range, failsafe biasing, termination and unit loads.', 'href': 'https://www.ti.com/lit/an/slla272d/slla272d.pdf', 'meta': 'Texas Instruments · PDF'}, CAN]},

 {'id': 'sku6', 'slug': 'sku-6', 'code': 'SKU-6', 'sheet': '7', 'name': 'quad-rail voltage supervisor',
  'title': 'SKU-6 quad-rail voltage supervisor system architecture',
  'subtitle': 'Four sense chains, a latched fault matrix, open-drain outputs, a trimmed reference and a windowed watchdog · from Technical Annex v3, sheet 7',
  'frame': 'SKU-6  ·  130 nm CMOS prototype, 180 nm production',
  'differs': 'the watchdog window (1 ms / 10 ms on the sheet, adjustable 100 ms to 1.6 s here), the oscillator (RC 8 MHz on the sheet, 1 MHz here) and the fourth rail (1V2 on the sheet, 1.2 / 0.9 V adjustable here)', 'about': 'SKU-6 watches four supply rails and the processor that depends on them. Each rail runs through a matched divider, a chopper-stabilised comparator and a digital deglitch counter into a latched fault matrix that drives FAULT_N and RESET_N; a windowed watchdog catches a hung or runaway processor.',
  'rows': [
   {'h': 380, 'zones': [
     {'key': 'Z1', 'name': 'Sense chain · one per rail', 'color': 'blue', 'cols': 4, 'w': 2.4,
      'what': 'For each of four rails: an ESD-protected input, a 0.1%-matched polysilicon divider, a chopper-stabilised comparator with 8 mV hysteresis, and an 8 µs digital deglitch counter.',
      'why': 'Switching noise must not trip a reset, yet a real fault must still be caught quickly; the deglitch counter does both.',
      'blocks': [('V1', 'VIN 1', '5V0 · ESD 2 kV'), ('D1', 'Divider', 'poly R ladder · 0.1% match'), ('C1', 'Comparator', 'chopper-stabilised · ±1% · 8 mV hyst'), ('G1', 'Deglitch', 'digital counter · 8 µs'),
                 ('V2', 'VIN 2', '3V3 · ESD 2 kV'), ('D2', 'Divider', 'poly R ladder · 0.1% match'), ('C2', 'Comparator', 'chopper-stabilised · ±1% · 8 mV hyst'), ('G2', 'Deglitch', 'digital counter · 8 µs'),
                 ('V3', 'VIN 3', '1V8 · ESD 2 kV'), ('D3', 'Divider', 'poly R ladder · 0.1% match'), ('C3', 'Comparator', 'chopper-stabilised · ±2% · 8 mV hyst'), ('G3', 'Deglitch', 'digital counter · 8 µs'),
                 ('V4', 'VIN 4', '1.2 / 0.9 V adjustable · ESD 2 kV'), ('D4', 'Divider', 'poly R ladder · 0.1% match'), ('C4', 'Comparator', 'chopper-stabilised · ±2% · 8 mV hyst'), ('G4', 'Deglitch', 'digital counter · 8 µs')]},
     {'key': 'Z2', 'name': 'Fault logic', 'color': 'purple', 'cols': 1, 'w': 0.7,
      'what': 'A maskable, latched fault matrix with a priority encoder, mask register, latch and I²C registers.',
      'blocks': [('FM', 'Fault matrix', 'maskable · latched · priority enc · mask reg · latch · I²C regs')]},
     {'key': 'Z3', 'name': 'Output stage', 'color': 'grey', 'cols': 1, 'w': 0.8,
      'what': 'Open-drain FAULT_N, which asserts before RESET_N, an open-drain RESET_N with a trimmed 200 ms delay, and a manual-reset input.',
      'blocks': [('RST', 'RESET_N', 'open-drain · 200 ms delay, trimmed'), ('FLT', 'FAULT_N', 'open-drain · asserts before RESET_N'), ('MR', 'MR / manual', 'push-button in')]},
   ]},
   {'h': 170, 'zones': [
     {'key': 'Z4', 'name': 'Reference + timebase', 'color': 'green', 'cols': 3, 'w': 1.4,
      'what': 'A curvature-corrected bandgap at 1.20 V and 10 ppm/°C, a 5-bit OTP trim to ±0.5%, and a 1 MHz oscillator with a reference current.',
      'why': 'The bandgap and trimmed polysilicon resistors are what make the threshold accuracy possible on a mature node.',
      'blocks': [('BG', 'Bandgap', 'curvature-corrected · 1.20 V · 10 ppm/°C · PTAT + CTAT'), ('TRIM', 'Trim', 'OTP 5-bit · ±0.5% after trim'), ('OSC', 'Osc', '1 MHz · ±2% over −40 to 125 °C · ref current')]},
     {'key': 'Z5', 'name': 'Watchdog', 'color': 'red', 'cols': 3, 'w': 1,
      'what': 'A windowed watchdog adjustable from 100 ms to 1.6 s: an open and close window, a kick input, and a timeout counter that drives RESET_N.',
      'blocks': [('WL', 'Window logic', 'open + close · 100 ms to 1.6 s'), ('WDI', 'WDI', 'kick input'), ('TO', 'Timeout', 'counter → RESET_N')]},
   ]},
  ],
  'edges': [('V1', 'D1', '①', 'blue'), ('D1', 'C1', '', 'blue'), ('C1', 'G1', '', 'blue'), ('G1', 'FM', '②', 'blue'), ('FM', 'FLT', '③', 'purple'), ('Z4', 'Z1', '④', 'green', 'exitX=0.5;exitY=0;entryX=0.62;entryY=1;'), ('WDI', 'TO', '', 'red'), ('TO', 'Z3', '⑤', 'red', 'exitX=0.5;exitY=0;entryX=0.5;entryY=1;')],
  'markers': [('①', 'Each rail enters through its divider.'), ('②', 'The comparator and deglitch counter report a confirmed fault to the matrix.'), ('③', 'The matrix latches it and drives FAULT_N, then RESET_N.'),
              ('④', 'The trimmed bandgap sets every comparator threshold.'), ('⑤', 'A missed or early watchdog kick times out to RESET_N.')],
  'toward': ['MIL-STD-883K Class B screening flow'],
  'alt': 'SKU-6 voltage supervisor architecture diagram: four rail sense chains into a latched fault matrix, open-drain FAULT_N and RESET_N outputs, a trimmed reference and timebase, and a windowed watchdog',
  'caption': 'Redrawn from the Technical Annex v3, sheet 7, with the watchdog range from the product specification. Numbered markers trace a rail fault to FAULT_N and RESET_N.',
  'background': [BROKAW, HERCULES]},

 {'id': 'sku7', 'slug': 'sku-7', 'code': 'SKU-7', 'sheet': '8', 'name': '77 GHz MIMO radar',
  'title': 'SKU-7 77 GHz MIMO radar system architecture',
  'subtitle': 'A SiGe HBT front end for chirp synthesis, transmit and four receive channels, and a 130 nm CMOS baseband for FFTs, detection and tracking · from Technical Annex v3, sheet 8',
  'frame': 'SKU-7  ·  two dies: SiGe HBT front end (IHP SG13G2) + 130 nm CMOS baseband at 200 MHz',
  'output': 'To the ECU · CAN-FD · 100BASE-T1 · MIPI CSI-2',
  'differs': 'the ECU interfaces (the sheet names CAN-FD and Ethernet; this page states CAN-FD, 100BASE-T1 and MIPI CSI-2) and the converters (drawn with the SiGe receive chain on the sheet; on the CMOS die here)', 'about': 'SKU-7 is a two-transmit, four-receive FMCW radar for the 76 to 81 GHz band. A SiGe HBT die synthesises the chirp, transmits it and mixes the four echoes down; a 130 nm CMOS die digitises the result and runs range and Doppler FFTs, CFAR detection, angle estimation and a target list.',
  'rows': [
   {'h': 210, 'zones': [
     {'key': 'Z1', 'name': 'Chirp synthesis + transmit · SiGe die', 'color': 'amber', 'cols': 4, 'w': 1.5, 'dashed': False,
      'what': 'A 40 MHz crystal, a ramp generator, a fractional-N PLL, a 38.5 GHz SiGe VCO and a doubler to 77 GHz, feeding two 13 dBm power amplifiers.',
      'why': 'A 4 GHz sweep gives 3.75 cm range resolution, and only a SiGe HBT reaches 77 GHz on a mature node.',
      'blocks': [('XT', 'XTAL', '40 MHz'), ('RG', 'Ramp gen', 'chirp profile · sawtooth / triangle'), ('PLL', 'PLL', 'fractional-N · 1 MHz loop BW'), ('VCO', 'VCO', '38.5 GHz · SiGe HBT'),
                 None, ('PA2', 'PA · TX2', '13 dBm'), ('PA1', 'PA · TX1', '13 dBm'), ('X2', '× 2', '77 GHz')]},
     {'key': 'Z2', 'name': 'Signal processing · CMOS die', 'color': 'green', 'cols': 2, 'w': 1,
      'what': 'Four 12-bit 40 MSPS converters digitise the IF signals as they cross the die boundary; windowing, a 1024-point radix-4 range FFT, a 128-point Doppler FFT and a range-Doppler map in 512 KB of SRAM follow.',
      'blocks': [('ADC', 'ADC × 4', '12-bit · 40 MSPS'), ('WIN', 'Windowing', 'Hann / Blackman'), ('DF', 'Doppler FFT', '128-pt across chirps · velocity bins'), ('RF', 'Range FFT', '1024-pt radix-4 · 26 µs per chirp'), ('RD', 'Range-Doppler', 'map buffer · SRAM 512 KB', 2)]},
   ]},
   {'h': 210, 'zones': [
     {'key': 'Z3', 'name': 'Receive array · 4 channels · SiGe die', 'color': 'blue', 'cols': 4, 'w': 1.5,
      'what': 'Four identical channels: a 3.5 dB noise-figure LNA, a mixer fed by the LO, an IF amplifier and a 10 MHz anti-alias filter; the IF signals leave the SiGe die for the converters.',
      'why': 'The beat frequency carries range; the phase across the four receivers carries the angle of arrival.',
      'blocks': [('LNA', 'LNA × 4', '3.5 dB NF'), ('MIX', 'Mixer × 4', 'LO from the × 2'), ('IF', 'IF amp × 4', ''), ('AAF', 'AAF × 4', '10 MHz LP')]},
     {'key': 'Z4', 'name': 'Detection + output · CMOS die', 'color': 'purple', 'cols': 2, 'w': 1,
      'what': 'Cell-averaging CFAR detection, digital-beamforming angle estimation at 15° resolution from four receivers, and a target list of up to 64 tracks per frame.',
      'blocks': [('AE', 'Angle est', 'digital beamform · 4 RX → 15° res'), ('CF', 'CFAR', 'cell-averaging · constant false-alarm'), ('TL', 'Target list', 'range · velocity · angle · RCS · up to 64 tracks per frame', 2)]},
   ]},
  ],
  'edges': [('XT', 'RG', '①', 'amber'), ('RG', 'PLL', '', 'amber'), ('PLL', 'VCO', '', 'amber'), ('VCO', 'X2', '', 'amber'), ('X2', 'PA1', '②', 'red'), ('PA1', 'PA2', '', 'red'), ('X2', 'MIX', 'LO', 'purple', 'exitX=0.5;exitY=1;entryX=0.5;entryY=0;'), ('LNA', 'MIX', '③', 'blue'), ('MIX', 'IF', '', 'blue'), ('IF', 'AAF', '', 'blue'), ('AAF', 'ADC', '④', 'amber', 'exitX=1;exitY=0.5;entryX=0;entryY=0.5;'), ('ADC', 'WIN', '', 'green'), ('WIN', 'RF', '', 'green'),
            ('RF', 'DF', '', 'green'), ('DF', 'RD', '', 'green'), ('RD', 'CF', '⑤', 'purple'), ('CF', 'AE', '', 'purple'), ('TL', 'OUT', '⑥', 'main')],
  'markers': [('①', 'The crystal, ramp generator, PLL and VCO synthesise the chirp.'), ('②', 'The doubler reaches 77 GHz and the two PAs transmit.'), ('③', 'Each of four echoes is amplified, mixed with the LO, filtered.'),
              ('④', 'The IF signals cross the die boundary and four 12-bit converters digitise them for the range FFT.'), ('⑤', 'The range-Doppler map feeds CFAR detection and angle estimation.'), ('⑥', 'The target list goes to the ECU over CAN-FD, 100BASE-T1 or MIPI CSI-2.')],
  'toward': ['ISO 26262 ASIL-B', 'DO-160G', 'MIL-STD-883K'],
  'alt': 'SKU-7 radar architecture diagram: chirp synthesis and two transmitters and a four-channel receive array on a SiGe die, range and Doppler processing and detection on a 130 nm CMOS die',
  'caption': 'Redrawn from the Technical Annex v3, sheet 8. Numbered markers trace one chirp from synthesis to the target list. Values are design targets.',
  'background': [{'title': 'The fundamentals of millimeter wave radar sensors (TI SPYY005)', 'note': 'FMCW chirps, beat frequency, range and velocity FFTs and angle estimation.', 'href': 'https://www.ti.com/lit/wp/spyy005a/spyy005a.pdf', 'meta': 'Texas Instruments · PDF'},
                 {'title': 'IHP SG13G2 open PDK', 'note': 'The open SiGe BiCMOS process the front end is drawn on.', 'href': 'https://github.com/IHP-GmbH/IHP-Open-PDK', 'meta': 'IHP · GitHub'}]},

 {'id': 'sku8', 'slug': 'sku-8', 'code': 'SKU-8', 'sheet': '9', 'name': 'rugged display driver and TCON',
  'title': 'SKU-8 rugged display driver and TCON system architecture',
  'subtitle': 'Video input, a temperature-compensated pixel pipeline and timing on a control bus, driving 1280 high-voltage column outputs and the row and backlight drivers · from Technical Annex v3, sheet 9',
  'frame': 'SKU-8  ·  130 nm high-voltage CMOS  ·  200 MHz',
  'input': 'LVDS · MIPI DSI · parallel RGB',
  'output': 'To the panel · source / gate / VCOM / LED',
  'differs': 'the gamma table (10-bit per channel on the sheet, a 14-bit table here), the LVDS input (4 lanes + clock on the sheet, dual link at 655 Mbps per lane here), the MIPI DSI input (2 lanes at 1.5 Gbps on the sheet, four lanes here) and the PLL (108 MHz on the sheet, 100 MHz here)', 'about': 'SKU-8 combines a timing controller and a 1280-column source driver for rugged TFT panels. It receives video over LVDS or MIPI DSI, linearises, colour-corrects, gamma-maps and dithers it, and drives each column through a 10-bit DAC and a high-voltage output amplifier, with row, VCOM and backlight control alongside.',
  'rows': [
   {'h': 230, 'zones': [
     {'key': 'Z1', 'name': 'Video input', 'color': 'blue', 'cols': 2, 'w': 1,
      'what': 'Dual-link LVDS at 655 Mbps per lane and four-lane MIPI DSI receivers into a dual-port line buffer of four 1280-pixel, 24-bit lines.',
      'blocks': [('LV', 'LVDS RX', 'dual link · 655 Mbps per lane · SXGA 1280 × 1024 @ 60 Hz'), ('DSI', 'DSI RX', 'four-lane MIPI DSI'), ('LB', 'Line buffer', 'dual-port SRAM · 4 lines × 1280 × 24 bit', 2)]},
     {'key': 'Z2', 'name': 'Pixel pipeline', 'color': 'purple', 'cols': 2, 'w': 1.2,
      'what': 'De-gamma, a 3 × 3 colour matrix with white point, a 14-bit gamma table with temperature feedback, and temporal and spatial dithering.',
      'why': 'LCD response shifts with panel temperature, so the gamma is temperature-compensated.',
      'blocks': [('DG', 'De-gamma', 'input linearise'), ('COL', 'Colour', '3 × 3 matrix + WP'), ('DI', 'Dither', 'temporal + spatial'), ('GL', 'Gamma LUT', '14-bit table · temperature feedback')]},
     {'key': 'Z3', 'name': 'Timing + test', 'color': 'amber', 'cols': 2, 'w': 1,
      'what': 'A timing controller with programmable porches, a 100 MHz pixel-clock PLL, a colour-bar test pattern and frame-freeze detection that alerts within two frames.',
      'blocks': [('TC', 'TCON', 'H/V timing gen · programmable porches'), ('PLL', 'PLL', 'pixel clock · 100 MHz'), ('TP', 'Test pattern', 'colour bars'), ('BIST', 'BIST + safety', 'frame-freeze detect')]},
   ]},
   {'bus': 'Control bus  ·  SPI / I²C register file  ·  200 MHz'},
   {'h': 230, 'zones': [
     {'key': 'Z4', 'name': 'Column (source) drivers · high-voltage', 'color': 'red', 'cols': 3, 'w': 1.6,
      'what': 'One 10-bit resistor-string DAC per column and rail-to-rail high-voltage amplifiers swinging 0 to 12 V, driving 3,840 sub-pixel outputs with charge-sharing precharge.',
      'why': 'A 0 to 12 V swing on thick oxide is mature-node territory; precharge cuts driver power by about 40%.',
      'blocks': [('DAC', 'DAC bank', '10-bit, 1 per column · resistor-string + buffer'), ('OA', 'Output amps', 'rail-to-rail HV · 0 to 12 V swing, thick oxide'), ('CO', 'Column outputs × 1280', '3 sub-pixels × 1280 → 3,840 outputs · charge-sharing precharge')]},
     {'key': 'Z5', 'name': 'Row + backlight', 'color': 'green', 'cols': 2, 'w': 1,
      'what': 'A gate-driver interface with a 24 V level shift, the VCOM electrode, an LED backlight with eight local-dimming zones, and ambient light and temperature sensing.',
      'blocks': [('GD', 'Gate driver IF', 'row scan · up to 24 V level shift'), ('VC', 'VCOM', 'common electrode'), ('BL', 'Backlight', 'PWM + LED string · local dimming, 8 zones'), ('AMB', 'Ambient', 'light + temp sense')]},
   ]},
  ],
  'edges': [('IN', 'LV', '①', 'green'), ('LV', 'LB', '', 'blue'), ('LB', 'Z2', '②', 'blue', 'exitX=1;exitY=0.5;entryX=0;entryY=0.3;'), ('DG', 'COL', '', 'purple'), ('COL', 'GL', '', 'purple'), ('GL', 'DI', '', 'purple'), ('DI', 'Z4', '③', 'purple', 'exitX=0.5;exitY=1;entryX=0.3;entryY=0;'), ('DAC', 'OA', '', 'red'), ('OA', 'CO', '④', 'red'), ('Z3', 'Z5', '⑤', 'amber', 'exitX=0.5;exitY=1;entryX=0.5;entryY=0;'), ('Z4', 'OUT', '', 'main', 'exitX=0.75;exitY=1;entryX=0;entryY=0.5;')],
  'markers': [('①', 'Video arrives over LVDS, MIPI DSI or parallel RGB.'), ('②', 'The line buffer feeds the pixel pipeline, 24 bits per pixel.'), ('③', 'Dithered pixels drive the column DACs.'),
              ('④', 'High-voltage amplifiers drive the 3,840 column outputs.'), ('⑤', 'The timing controller scans the rows through the gate driver.')],
  'toward': ['ISO 26262 ASIL-B', 'MIL-STD-810G', 'DEF-STAN 00-35'],
  'alt': 'SKU-8 display driver architecture diagram: video input, pixel pipeline and timing and test on a control bus, high-voltage column drivers, and row and backlight control',
  'caption': 'Redrawn from the Technical Annex v3, sheet 9, with the gamma depth from the product specification. Numbered markers trace a frame from video input to the panel.',
  'background': [{'title': 'LVDS Owner’s Manual (TI SNLA187)', 'note': 'How LVDS links carry video, and their timing and termination.', 'href': 'https://www.ti.com/lit/ug/snla187/snla187.pdf', 'meta': 'Texas Instruments · PDF'},
                 {'title': 'MIPI DSI specification overview', 'note': 'The display serial interface on the second receiver.', 'href': 'https://www.mipi.org/specifications/dsi', 'meta': 'MIPI Alliance'}]},

 {'id': 'sku9', 'slug': 'sku-9', 'code': 'SKU-9', 'sheet': '10', 'name': 'zonal controller and gateway',
  'title': 'SKU-9 zonal controller and gateway system architecture',
  'subtitle': 'A lockstep safety island, a security module and real-time control on a 64-bit AXI4 crossbar, bridging in-vehicle networks to sixteen smart fuses · from Technical Annex v3, sheet 10',
  'frame': 'SKU-9  ·  130 nm CMOS and BCD  ·  100 MHz',
  'banner': 'Scope, as the sheet states it: 130 nm at 100 MHz owns the zonal layer: gateway, smart I/O, safety and security edge. Central software-defined-vehicle compute is a sub-10 nm part and is not claimed here.',
  'output': 'To the zone harness · loads, sensors, actuators',
  'differs': 'the network ports (the sheet draws CAN-XL × 2, FlexRay × 2 and a 1000BASE-T1 port; this page states one CAN-XL, one FlexRay and no 1000BASE-T1)', 'about': 'SKU-9 is the zonal edge of a software-defined vehicle. It receives messages on Ethernet, CAN and LIN, schedules them with time-sensitive networking, and turns them into switched power at sixteen smart fuses, with a lockstep safety island and a hardware security module across every path.',
  'rows': [
   {'h': 230, 'zones': [
     {'key': 'Z1', 'name': 'Safety island', 'color': 'red', 'tone': 'safe', 'cols': 2, 'w': 1,
      'what': 'Two DGridRiscV cores in lockstep with a two-cycle skew, memory protection and ECC, a bus and retire comparator, and a freedom-from-interference firewall.',
      'why': 'Safety-critical and comfort functions share one chip, so the island is isolated by an MPU and a bus firewall.',
      'blocks': [('CPU', 'DGridRiscV × 2', 'RV32IM_Zicsr · lockstep · 100 MHz · +2 cycle skew · PMP · ECC'), ('CMP', 'Comparator', 'bus + retire · mismatch → safe state'), ('FFI', 'Freedom from interference', 'MPU + bus firewall', 2)]},
     {'key': 'Z2', 'name': 'Security', 'color': 'purple', 'cols': 2, 'w': 1,
      'what': 'A hardware security module with AES-256 and ECC-256, secure boot from an OTP key store with A/B slots, and an OTA engine with signed-image verification and rollback.',
      'blocks': [('HSM', 'HSM', 'hardware security module · AES-256 · ECC-256 · true RNG'), ('SB', 'Secure boot', 'root of trust · OTP key store · A/B slots'), ('OTA', 'OTA engine', 'signed image verify + rollback', 2)]},
     {'key': 'Z3', 'name': 'Real-time control', 'color': 'blue', 'cols': 2, 'w': 1,
      'what': 'A TSN switch with an 802.1Qbv time-aware shaper, 802.1AS precision time, and a SOME/IP and DoIP service router.',
      'why': 'Brake-by-wire messages need bounded latency on a shared link.',
      'blocks': [('TSN', 'TSN switch', '802.1Qbv · time-aware shaper'), ('PTP', 'PTP', '802.1AS clock · sub-µs sync'), ('SR', 'Service router', 'SOME/IP + DoIP', 2)]},
   ]},
   {'bus': 'AXI4 crossbar  ·  64-bit  ·  100 MHz'},
   {'h': 190, 'zones': [
     {'key': 'Z4', 'name': 'In-vehicle network · gateway', 'color': 'green', 'cols': 3, 'w': 1.5,
      'what': 'The gateway ports: two 100BASE-T1, eight CAN-FD, one CAN-XL, eight LIN and one FlexRay. The gateway routes and rate-limits between domains.',
      'blocks': [('ETH', '100BASE-T1 × 2', 'automotive Ethernet'), ('CANFD', 'CAN-FD × 8', ''), ('CANXL', 'CAN-XL × 1', ''), ('LIN', 'LIN × 8', 'masters'), ('FR', 'FlexRay × 1', '')]},
     {'key': 'Z5', 'name': 'Zonal power + I/O', 'color': 'amber', 'cols': 2, 'w': 1,
      'what': 'Sixteen smart electronic fuses with sensing, eight high-side drivers, a 24-channel 12-bit sense ADC and twelve PWM actuator outputs.',
      'why': 'Switching 12 V and 48 V loads in the harness needs BCD power devices beside the logic.',
      'blocks': [('FUSE', 'Smart fuse × 16', 'eFuse + sense · replaces relay box'), ('HS', 'HS driver × 8', 'load control'), ('ADC', 'ADC 12-bit', '24-ch sense'), ('PWM', 'PWM × 12', 'actuator drive')]},
   ]},
  ],
  'edges': [('CANFD', 'BUS', '①', 'green'), ('TSN', 'PTP', '②', 'blue'), ('SR', 'BUS', '③', 'blue'), ('BUS', 'FUSE', '④', 'amber'), ('Z5', 'OUT', '', 'amber'), ('CMP', 'FFI', '⑤', 'red')],
  'markers': [('①', 'Messages arrive on Ethernet, CAN and LIN.'), ('②', 'The TSN switch schedules them against precision time.'), ('③', 'The service router forwards them across the crossbar.'),
              ('④', 'They become switched power at the smart fuses.'), ('⑤', 'A lockstep mismatch drives the safe state.')],
  'toward': ['ISO 26262 ASIL-D', 'EVITA Full', 'AUTOSAR Classic 4.4', 'AEC-Q100 Grade 1'],
  'alt': 'SKU-9 zonal controller architecture diagram: a lockstep safety island, security and real-time control on a 64-bit AXI4 crossbar, the in-vehicle network gateway and zonal power and I/O',
  'caption': 'Redrawn from the Technical Annex v3, sheet 10, with network counts from the product specification. Numbered markers trace a message from the vehicle network to a switched load.',
  'background': [{'title': 'IEEE 802.1Qbv: enhancements for scheduled traffic', 'note': 'The time-aware shaper behind bounded-latency TSN.', 'href': 'https://standards.ieee.org/ieee/802.1Qbv/6068/', 'meta': 'IEEE Standards'}, CAN, HERCULES, AMBA]},
]
