// GENERATED by scripts/sku-diagrams/stories.py from the story-architect storyboards (content-ideas runs/2026-10-03-arch-storyboards). Edit the storyboard JSON, then regenerate.
import type {ArchStory} from './detail';

export const archStories: Record<string, ArchStory> = {
 "sku1": {
  "id": "sku1",
  "headline": "One chip runs the motor loop and controls its supply up to 120 V",
  "lead": "A brushless drive today pairs a microcontroller running the loop in firmware with a separate gate pre-driver. SKU-1 puts both on one 130 nm BCD die, so a 16-bit ADC sits beside a switching half-bridge and the control loop must close in under a microsecond. The diagram shows how the loop stays in hardware.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "The host takes commands but stays out of the loop",
    "body": "Speed, torque, halt, brake and ramp commands arrive at Host interfaces and the DGridRiscV core, a 100 MHz RISC-V with SRAM, ReRAM for secrets and Timers · WDT · CCU beside it; firmware sits in external flash. The core configures the loop and supervises it over the AXI bus. It does not sit in the loop, so firmware timing never decides when the gates switch.",
    "zones": [
     "Host · control plane"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "The torque command becomes phase drive in hardware",
    "body": "In the Field-oriented control datapath, the PID tuner sets the correction, Rect → polar turns it into magnitude and angle with a CORDIC, d,q → 3-phase applies inverse Park and Clarke, and Sine / trapezoid picks sinusoidal or six-step drive. Because the loop is hardware, its latency is fixed, with a target under 1 µs.",
    "zones": [
     "Field-oriented control datapath"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "PWM switches three half-bridges on a motor supply up to 120 V",
    "body": "PWM × 7 drives the Pre-drivers R / Y / B: six channels for the bridge and one auxiliary, up to 200 kHz. The chip controls the motor supply from 5 V to 120 V: up to about 20 V the gate drive sits on the die, and above it the chip drives external power switches. Star / delta selects the winding at runtime.",
    "zones": [
     "Power path"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "Current and angle feedback closes the loop on the die",
    "body": "Hall / quad / enc inputs feed Angle (ω) for rotor position and speed. iR iY iB rebuild and Instant current reconstruct the three phase currents, which CSA × 3 amplify and the 16-bit ADC digitises in the Mixed signal zone. The feedback returns to the PID tuner, so the loop closes without a round trip through firmware.",
    "zones": [
     "Sensor + feedback",
     "Mixed signal"
    ]
   },
   {
    "marks": [
     "F"
    ],
    "title": "A fault shuts the gates and the trip stays latched",
    "body": "Protection watches for thermal, overcurrent and overvoltage faults. On any of them it shuts the gate drive at the Pre-drivers R / Y / B, and the shutdown is latched: it holds after the fault passes instead of switching the bridge back on by itself. Above it, the watchdog in Timers · WDT · CCU supervises the processor.",
    "zones": [
     "Power path",
     "Host · control plane"
    ]
   }
  ],
  "closing": {
   "title": "Isolation and loop timing are still to be proven",
   "body": "SKU-1 is pre-silicon and every figure here is a target. Evaluation should settle four questions: isolating the 16-bit ADC from 10 V/ns switching edges, the 1 µs deadline under CAN-FD bus load, ReRAM retention above 125 °C junction, and dead-time as gate thresholds drift."
  },
  "sections": {
   "physics": {
    "title": "A motor supply up to 120 V sets where SKU-1’s gate drive sits",
    "copy": "Up to about 20 V the gate drive, regulator and processor share one 130 nm BCD die; higher rails, up to 120 V, use external power switches the chip drives. An advanced node would push even the gate drive back onto the board. The same die carries a 16-bit ADC beside the switching stage and a loop that must close in under 1 µs."
   },
   "specs": {
    "title": "Loop time and rail span decide SKU-1, and both are still targets",
    "copy": "Read three rows first: the hardware PID under 1 µs, the 5 V to 120 V motor supply and seven PWM channels to 200 kHz. They set what the drive can switch. Every row is a target from the SKU Blueprint, October 2026, page 10, none measured."
   },
   "questions": {
    "title": "Isolation and timing answers decide if SKU-1 can replace two chips",
    "copy": "Substrate isolation and dead-time decide whether the 16-bit ADC and the on-die gate drive can share a die. The 1 µs deadline under CAN-FD load decides whether firmware stays out of the loop. ReRAM retention above 125 °C junction decides whether stored secrets survive."
   },
   "fit": {
    "title": "SKU-1 turns a driver-plus-MCU drive into one die beside SKU-4",
    "copy": "It goes into fans, appliances, EV two- and three-wheelers, robotics and actuator joints, replacing a motor-driver chip plus a separate microcontroller. SKU-4 supervises the drive and can shut it down; D100 drives its flight motors through the ESC path."
   },
   "evidence": {
    "title": "SKU-1’s control datapath runs on FPGA; its analog circuits are simulated",
    "copy": "The motor control datapath runs as circuit code on an Artix-7 at 81.25 MHz, and the analog gate-drive and sensing circuits are designed and simulated (schematic and SPICE). Nothing has been measured on silicon. SKU-1 is pre-silicon, with its prototype on the December 2026 shuttle; the fan-and-appliance cut is a second tape-out on the same RTL."
   },
   "sources": {
    "title": "The SKU Blueprint sizes SKU-1; the whitepaper shows its FPGA run",
    "copy": "The SKU Blueprint, October 2026, page 10, holds the architecture targets, status and what the part replaces. The whitepaper names the FPGA-validated motor control datapath. Technical Annex v3, sheet 2, the earlier edition, carries the original block diagram."
   },
   "close": {
    "title": "Bring your motor and bus voltage, and we will scope SKU-1 against them",
    "copy": "Bring the motor topology and power, the motor supply up to 120 V, the gate-drive and dead-time needs, the control-loop rate, the feedback you have (Hall, quadrature or encoder) and your protection requirements. The reply names what SKU-1 must prove for that drive."
   }
  }
 },
 "sku2": {
  "id": "sku2",
  "headline": "A meter that keeps measuring and keeps its record without mains",
  "lead": "A meter today pairs a metrology front end with a separate meter microcontroller, so two supply domains must stay alive on a backup cell and the clock lives apart from the measurement it timestamps. SKU-2 puts measurement, security and an always-on time base on one 130 nm die. The diagram follows one reading from sense pin to UART.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "Six sense channels enter one 24-bit front end",
    "body": "Voltage and current from the V / I sense inputs, six channels in all, enter DG-AFE6 in the Metrology zone: six 24-bit sigma-delta converters. The converter sets billing accuracy, so it is dedicated hardware with low flicker noise and stable references, calibrated once. The design is developed toward Class 0.5S across a 1000:1 current range.",
    "zones": [
     "Metrology"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "DECIM turns the raw bit stream into clean samples",
    "body": "DECIM filters each 24-bit sigma-delta stream through a sinc³ decimator at an oversampling ratio of 256, so every channel reaches the metrology engine as a clean, lower-rate sample. Doing this in hardware keeps the filtering off the processor and keeps the measurement chain fixed from the sense pin to the energy figure.",
    "zones": [
     "Metrology"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "METRO computes power and harmonics in hardware",
    "body": "METRO turns the samples into the figures a meter bills on: active, reactive and apparent power, P, Q and S, and total harmonic distortion to the 15th harmonic. Billing accuracy depends on the converter and the arithmetic together, which is why both sit in the Metrology zone rather than in firmware on the core.",
    "zones": [
     "Metrology"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "Results cross the bus to be stored and signed",
    "body": "Results cross the 32-bit AHB-Lite multilayer bus to the Compute + security zone. The DGridRiscV core at 100 MHz and the four-channel DMA move and store them, and DG-SE, with AES-256 and SHA-256, protects the record. Secure boot and tamper key erase guard the code and keys the readings depend on.",
    "zones": [
     "Compute + security"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "Readings leave the meter on the DLMS/COSEM UART",
    "body": "In the Peripherals row, the UART carries readings out in DLMS/COSEM, the metering protocol. Beside it, the LCD drives a 4 × 40 segment display, the Timer handles capture and compare, and GPIO switches the relay and LED. One die now covers measurement, security and the meter’s own interfaces.",
    "zones": [
     "Peripherals"
    ]
   },
   {
    "marks": [],
    "title": "The always-on domain keeps time and tamper state alive",
    "body": "PMU + RTC in the Always-on zone runs from a 32.768 kHz crystal and a 2.2 to 3.6 V backup cell, drawing under 2 µW, isolated from the 100 MHz core. The RTC keeps a tamper log and Tamper watches the case and magnet inputs, so the clock and the tamper record survive when the mains is gone.",
    "zones": [
     "Always-on",
     "Peripherals"
    ]
   }
  ],
  "closing": {
   "title": "Lifetime accuracy and outage leakage are still open",
   "body": "SKU-2 is pre-silicon and every figure is a target. Evaluation should settle four questions: Class 0.5S across 1000:1 over a fifteen-year life, magnet and DC tamper, leakage into the always-on domain during a thirty-day outage, and which code-storage option ships first."
  },
  "sections": {
   "physics": {
    "title": "A meter must keep time on a backup cell, so SKU-2 isolates its clock",
    "copy": "Class 0.5S across a 1000:1 range demands a low-noise 24-bit sigma-delta front end, calibrated once. The clock and tamper log must survive outages, so an always-on domain draws under 2 µW apart from the 100 MHz core. With no embedded flash, code sits in ROM, ECC SRAM and encrypted external flash, with an SCL eNVM variant for sealed meters."
   },
   "specs": {
    "title": "SKU-2 rests on its 24-bit front end and its sub-2 µW clock domain",
    "copy": "Read the six-channel 24-bit sigma-delta front end, the Class 0.5S target and the under 2 µW always-on domain first: they set billing accuracy and outage survival. Every row is a design target from the SKU Blueprint, October 2026, page 13, not a measurement of silicon."
   },
   "questions": {
    "title": "Drift, tamper and outage leakage decide whether SKU-2 can bill",
    "copy": "Drift over fifteen years decides whether one calibration holds Class 0.5S. Magnet and DC tamper detection decides whether the meter meets a tender. Leakage through a thirty-day outage sizes the backup cell, and the first code-storage option decides whether external QSPI stays on the board."
   },
   "fit": {
    "title": "In a smart meter, SKU-2 replaces the front end and the meter MCU",
    "copy": "SKU-2 goes into electricity meters for Class 0.5S metrology with tamper logging on backup power. It replaces a metrology front end plus a separate meter microcontroller, so one chip carries measurement, security and time. SKU-5 adds the wired RS-485 meter bus; SKU-6 supervises brownout."
   },
   "evidence": {
    "title": "SKU-2’s measurement chain runs on FPGA; its analog front end is simulated",
    "copy": "The meter measurement chain runs as circuit code on an Artix-7 at 81.25 MHz, and the six-channel analog front end is designed and simulated (schematic and SPICE). The converters, references and under 2 µW domain have no silicon data yet. SKU-2 is pre-silicon, with its prototype on the December 2026 shuttle."
   },
   "sources": {
    "title": "The SKU Blueprint sets SKU-2’s targets; the whitepaper shows FPGA",
    "copy": "The SKU Blueprint, October 2026, page 13, holds the architecture targets, status and what the part replaces. The whitepaper names the FPGA-validated meter measurement chain. Technical Annex v3, sheet 3, the earlier edition, carries the original block diagram."
   },
   "close": {
    "title": "Bring your meter class and tamper list, and we will scope SKU-2 against them",
    "copy": "Bring the accuracy class, the channels you measure and their current range, the tamper events your tender names, the backup cell and the outage it must ride through, and your code-storage preference. The reply names what SKU-2 must prove for that meter."
   }
  }
 },
 "sku3": {
  "id": "sku3",
  "headline": "One die turns a 28 V bus into four sequenced, supervised rails",
  "lead": "Avionics and vehicle electronics draw power from a 28 V bus that carries 80 V surges and 100 V spikes, yet their board rails must come up in order and stay correct under radiation. SKU-3 does that on one 180 nm BCD die: input conditioning, a pre-regulator, four rails and an upset-hardened sequencer.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "Input conditioning keeps bus surges off the rails",
    "body": "The 28 V aircraft bus enters Input conditioning. EMI + TVS filters and clamps at 36 V, Ideal diode blocks reverse polarity, Inrush limits start-up current, and UVLO + OVLO locks out a bus that runs too low or too high, with hysteresis. The input spans 4.5 to 40 V continuous, with surges the rails must never see.",
    "zones": [
     "Input conditioning"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "The pre-regulator limits current on every cycle",
    "body": "The conditioned bus feeds the Pre-regulator · synchronous buck. Error amp with type-III compensation and PWM comp with slope compensation set the duty between 500 kHz and 2 MHz, Gate driver adds adaptive dead-time, and Power stage is an LDMOS half-bridge on 30 V devices. Peak-current-mode control means a downstream fault cannot run away.",
    "zones": [
     "Pre-regulator · synchronous buck"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "One pre-regulated output feeds four rail regulators",
    "body": "In Rail generation, Buck · 5 V delivers 2 A, Buck · 3.3 V delivers 3 A, LDO · 1.8 V delivers 500 mA and LDO · 1.2 / 0.9 V delivers 300 mA. Each one starts on a soft-start ramp, so the board supplies come up under control instead of all at once from the pre-regulator output.",
    "zones": [
     "Rail generation"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "The sequencer decides when each rail may start",
    "body": "Each rail runs through a Window monitor, which flags over- and under-voltage outside a ±3% window, and an OC limit with foldback. Together they report power-good to the Sequencer in Supervision · sequencing · telemetry. The Sequencer follows a programmable four-step order and decides when each rail may start.",
    "zones": [
     "Rail generation",
     "Supervision · sequencing · telemetry"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "Current sense closes the fast inner loop",
    "body": "Current sense, a sense-FET and amplifier in the pre-regulator, feeds back to the Error amp and closes the peak-current-mode inner loop that limits current cycle by cycle. Its stability is still a question: the target is more than 60° phase margin and 10 dB gain margin across −55 to +125 °C with ceramic or tantalum capacitors.",
    "zones": [
     "Pre-regulator · synchronous buck"
    ]
   },
   {
    "marks": [],
    "title": "Hardened logic and a trimmed reference hold the sequence",
    "body": "SEU harden puts DICE latches and triple-modular redundancy on the sequencer state machine, so one particle strike cannot reorder or drop a rail. Watchdog adds a windowed check, and Telemetry reports voltage, current and die temperature through a 10-bit 500 kSPS ADC over SPI. In Reference + bias, a Brokaw Bandgap holds 12 ppm/°C, set by one-time OTP Trim.",
    "zones": [
     "Supervision · sequencing · telemetry",
     "Reference + bias"
    ]
   }
  ],
  "closing": {
   "title": "Surge withstand and upset spacing are not yet proven",
   "body": "SKU-3 is pre-silicon, prototyped on 130 nm before production at 180 nm, and every figure is a target. Evaluation should settle the 100 V, 50 ms surge clamp, loop margins across temperature, 3.3 V ripple reaching the 1.2 V converter, and upset spacing between voting bits."
  },
  "sections": {
   "physics": {
    "title": "A 100 V spike and a particle strike set SKU-3’s process and logic",
    "copy": "80 V surges and 100 V spikes on the input need 180 nm BCD with 30 V power devices. A 12 ppm/°C reference from −55 to +125 °C needs large matched resistors. One particle strike must not corrupt the sequence, so the sequencer is triple-redundant."
   },
   "specs": {
    "title": "Bus range, rail currents and the reference decide SKU-3’s fit",
    "copy": "Read the 4.5 to 40 V input range, the four rail currents and the 12 ppm/°C reference first: they decide whether SKU-3 matches your bus and board, in its military, railway or space grade. Every row is a target from the SKU Blueprint, October 2026, page 16, and the earlier annex sheet, not a measurement."
   },
   "questions": {
    "title": "Surge, stability and upset answers decide if SKU-3 holds a 28 V bus",
    "copy": "The 100 V, 50 ms surge clamp decides whether the input stage survives a load dump. Loop stability across −55 to +125 °C decides which output capacitors you may use. Cross-rail ripple sets the 1.2 V converter’s noise; upset spacing decides whether triple redundancy holds."
   },
   "fit": {
    "title": "SKU-3 takes the place of imported qualified power parts on 28 V",
    "copy": "It supplies the sequenced 28 V power rails of avionics and military-vehicle electronics, where imported qualified power parts sit today. On the same board it powers SKU-4 and its memory and the SKU-8 display bias rails, while SKU-6 independently supervises the rails it produces."
   },
   "evidence": {
    "title": "SKU-3’s control logic is RTL-ready; its power circuits are simulated",
    "copy": "RTL is ready for the digital sequencer and telemetry, and the analog power circuits are designed and simulated (schematic and SPICE). The December 2026 sky130 prototype tests the control logic and low-voltage rails; the 28 V front end and power stage arrive on SCL 180 nm. No surge, loop or upset figure has been measured, and the space grade is radiation-tolerant, not rad-hard, pending a TID/SEE campaign."
   },
   "sources": {
    "title": "The SKU Blueprint, page 16, sets SKU-3’s grades and status",
    "copy": "The SKU Blueprint, October 2026, page 16, sets the three grades, the status and what the part replaces. Technical Annex v3, sheet 4, the earlier edition, carries the input range, rails, reference and the four evaluation questions."
   },
   "close": {
    "title": "Bring your bus transients and rail list, and we will scope SKU-3 against them",
    "copy": "Bring the power bus with its surge and spike profile, the rails you need with their currents and start order, the temperature range, the output capacitors you plan to use, and the screening route your platform requires. The reply names what SKU-3 must prove."
   }
  }
 },
 "sku4": {
  "id": "sku4",
  "headline": "Two cores, two cycles apart, and a fault path that skips firmware",
  "lead": "A motor drive switches power electronics, and a silent fault in the processor produces a wrong PWM edge that can destroy a bridge. DG32-LITE, the implemented SKU-4 part, runs a second core two cycles behind the first and trips the bridge in hardware when they disagree. The diagram traces one current loop, then the fault path.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "The PWM fires the ADC where current ripple is lowest",
    "body": "3-phase PWM in Motor drive fires a sample trigger at the centre of each period, where current ripple is lowest. SAR ADC 8-bit in Sensing & math, differential at about 200 kSa/s, converts the phase current in 177 cycles. Because the converter is on the die, a sample costs a start pulse and a poll, not an external SPI read.",
    "zones": [
     "Motor drive",
     "Sensing & math"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "CORDIC runs the transforms at a fixed, known cost",
    "body": "Phase current goes to CORDIC, which runs the Clarke and Park transforms with the rotor angle from Encoder + Hall, whose edge timestamps keep velocity accurate at low speed. Each CORDIC operation takes 53 to 58 cycles. The CPU core is fetch-bound at about 8 cycles per instruction, so this math stays in hardware.",
    "zones": [
     "Sensing & math"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "The CPU keeps only the PI regulators",
    "body": "The transformed currents go to MAIN core in the Safety core, which runs the d and q PI regulators in plain C. With sampling, transforms and edge generation in hardware, one loop carries about 300 cycles of fixed hardware cost. At 10 kHz on the 50 MHz clock, that leaves about 4,700 of 5,000 cycles for firmware.",
    "zones": [
     "Safety core"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "New duty cycles load at the next period boundary",
    "body": "The PI output sets the duty in shadow registers in 3-phase PWM, and the new values load at the next period boundary, so an update never lands mid-period. Timers × 2 typically hold the control-loop period and an RTOS tick. DShot × 4 shares the same pads for digital ESC frames and is selected at boot.",
    "zones": [
     "Motor drive"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "Gate signals leave for a bridge outside the package",
    "body": "3-phase PWM drives six gate pins, centre-aligned and complementary with programmable dead-time, to the Gate driver + 3-phase bridge outside the QFN-64 package. A hardware brake forces all six outputs off within two clock cycles and latches, so firmware can see that it happened. The power stage itself never sits on the die.",
    "zones": [
     "Motor drive"
    ]
   },
   {
    "marks": [
     "F"
    ],
    "title": "A mismatch trips the bridge in 39 cycles, without firmware",
    "body": "CHECKER core runs the instructions of MAIN core two cycles later on the same inputs. Lockstep comparator checks every committed store; on the first mismatch, Fault latch holds the cause and drives FAULT_N low, which turns the Gate driver + 3-phase bridge off in hardware. From injected fault to latched FAULT_N took 39 cycles in simulation.",
    "zones": [
     "Safety core"
    ]
   },
   {
    "marks": [],
    "title": "Supervision and the bus keep every fault visible",
    "body": "Windowed watchdog faults a kick that arrives too early or too late, and its supply supervisor sequences reset. Interrupt controller delivers 16 sources identically to both cores, so CHECKER stays in step. On the On-chip bus, an unmapped address returns a bus error instead of a hang. Boot ROM 64 KB copies the image from QSPI NOR flash into SRAM 32 KB.",
    "zones": [
     "Supervision",
     "On-chip bus",
     "Memory & boot"
    ]
   }
  ],
  "closing": {
   "title": "Silicon has not yet confirmed the 39-cycle trip",
   "body": "DG32-LITE is pre-silicon: its figures come from simulation and post-route timing, and no fabricated part has been measured. Evaluation should settle how skewed reads and interrupts stay aligned across both cores, which self-tests reach the coverage a safety case needs, and what forces the PWM safe when FAULT_N asserts."
  },
  "sections": {
   "physics": {
    "title": "SKU-4 skews its cores two cycles so one transient cannot fool both",
    "copy": "A transient that hits both cores at once must still be caught, so the checker runs two cycles behind. The fault response cannot depend on the processor that failed, so comparator, latch and FAULT_N are hardware. Small, long-lived safety logic suits mature 130 nm CMOS."
   },
   "specs": {
    "title": "The 39-cycle trip is SKU-4’s key figure, and it is simulated",
    "copy": "Read the two-cycle lockstep and the 39 cycles from injected fault to latched FAULT_N first; they carry the safety argument. The product is a 130 nm chip at 100 MHz, validated on FPGA at 81.25 MHz; DG32-LITE, the earlier implemented part, ran at 50 MHz on QFN-64."
   },
   "questions": {
    "title": "Skew, coverage and safe state decide if SKU-4 can anchor a safety case",
    "copy": "Skewed reads and interrupt alignment decide whether both cores truly see the same inputs. Built-in self-test coverage decides whether the single-point fault metric a safety case needs is reachable. The PWM interlock decides whether FAULT_N forces a safe state with no software in the path."
   },
   "fit": {
    "title": "SKU-4 is the supervisor that can stop a drive another chip runs",
    "copy": "It goes beside SKU-1 in motor drives, in robot joints and EV battery management, and as flight-critical redundancy for D100. Because the drive and its supervisor are separate chips, a fault in one cannot silence the other. Braking and steering need CAN-FD, which DG32-LITE lacks."
   },
   "evidence": {
    "title": "DG32-LITE’s 39-cycle trip is simulated; no part has been measured",
    "copy": "Simulation and post-route implementation records exist for DG32-LITE, including the 39-cycle fault trip, and the product RTL is validated on FPGA at 81.25 MHz. No measured silicon result is published and no functional-safety certificate is claimed. The prototype is on the December 2026 shuttle; it is a plan, not returned silicon."
   },
   "sources": {
    "title": "DG32-LITE’s guide traces SKU-4’s fault path; the Blueprint sets the product",
    "copy": "The DG32-LITE Architecture Guide shows how the implemented part works: fault path, loop budget and post-route timing. The SKU Blueprint, October 2026, page 19, sets the product: 130 nm at 100 MHz, ROM and encrypted external flash, with embedded flash following on SCL 180 nm."
   },
   "close": {
    "title": "Bring your drive’s safe state, and we will scope DG32-LITE’s fault path for it",
    "copy": "Bring the fault response time your drive needs, its control-loop rate, the phase-current resolution the 8-bit ADC must meet, how FAULT_N reaches your gate-driver enable, and your QFN-64 board constraints. The reply names what SKU-4 must prove there."
   }
  }
 },
 "sku5": {
  "id": "sku5",
  "headline": "Two bus links on one die, built for what lands on the pins",
  "lead": "A bus transceiver meets the outside world: miswiring, ground shifts and electrostatic discharge land on its pins, and reach depends on edge timing more than bit rate. SKU-5 puts an RS-485 channel and a CAN-FD channel on one 130 nm die with 5 V thick-oxide outputs, so the analog blocks that matter sit where the bus needs them.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "Logic IF lifts 1.8 V logic to a 5 V bus driver",
    "body": "On channel 1, TXD enters Logic IF, which shifts the 1.8 V core logic up to 5 V and also carries RXD, enable and standby. The logic is a thin skin around the part: every block that decides how it behaves on the wire is analog, built on the thick-oxide devices a mature 130 nm process offers.",
    "zones": [
     "Channel 1 · RS-485  ·  half duplex · up to 256 nodes · −7 to +12 V CM"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "The pre-driver shapes each edge to buy reach",
    "body": "Pre-driver slews each edge at a trimmed 3 V/ns before it reaches the Output stage. On a bus, reach and node count depend on edge timing rather than the headline bit rate, so the edge is shaped and the delay is budgeted: 20 ns for the driver, 50 ns for the receiver, 70 ns for the loop.",
    "zones": [
     "Channel 1 · RS-485  ·  half duplex · up to 256 nodes · −7 to +12 V CM"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "Thick-oxide outputs drive the A / B pins",
    "body": "Output stage is a differential push-pull on thick-oxide 5 V LDMOS, driving A / B in the Bus pins column. RS-485 runs half duplex with up to 256 nodes over a −7 to +12 V common mode, at 20 Mbps over short runs or about 83 kbps at 1.2 km: two operating points, not one.",
    "zones": [
     "Channel 1 · RS-485  ·  half duplex · up to 256 nodes · −7 to +12 V CM",
     "Bus pins"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "The receiver reads the bus back with 30 mV hysteresis",
    "body": "Receiver, a hysteresis comparator with 30 mV of hysteresis and 50 ns propagation, reads A / B back to RXD. Failsafe bias holds an idle bus at recessive and detects open, short and idle conditions, so a dead or open bus reads as a known state instead of noise that the logic could mistake for data.",
    "zones": [
     "Channel 1 · RS-485  ·  half duplex · up to 256 nodes · −7 to +12 V CM",
     "Bus pins"
    ]
   },
   {
    "marks": [],
    "title": "Channel 2 repeats the same path for CAN-FD",
    "body": "Channel 2 mirrors the same blocks across the Bus pins column: Logic IF, Pre-driver, Output stage onto CANH / CANL, then Receiver and Failsafe bias. It targets an 8 Mbps data phase with a ±12 V common mode as drawn, and its Local supply + osc adds bit-time recovery from a 40 MHz reference.",
    "zones": [
     "Channel 2 · CAN-FD  ·  8 Mbps data · ISO 11898-2 · ±12 V CM",
     "Bus pins"
    ]
   },
   {
    "marks": [],
    "title": "Every pin that leaves the board carries its own protection",
    "body": "ESD + EMC structures guard A / B and CANH / CANL, with a ±15 kV target rated per test standard. Fault shuts a channel down on a short or at 150 °C. Prot logic interlocks the RS-485 enable so drivers never contend, and times out a stuck CAN transmit. Local supply + osc builds 3.3 V from the 5 V bus.",
    "zones": [
     "Channel 1 · RS-485  ·  half duplex · up to 256 nodes · −7 to +12 V CM",
     "Channel 2 · CAN-FD  ·  8 Mbps data · ISO 11898-2 · ±12 V CM"
    ]
   }
  ],
  "closing": {
   "title": "ESD survival and unit load have no silicon data yet",
   "body": "SKU-5 is pre-silicon and every figure is a target, designed toward TIA/EIA-485 and ISO 11898-2. Evaluation should settle which ESD structures hold ±15 kV on a dedicated test chip, how 256 nodes are reached and at what input impedance, and which discontinued part is the first drop-in."
  },
  "sections": {
   "physics": {
    "title": "SKU-5 meets ESD and miswiring at the pin, so it needs thick oxide",
    "copy": "Bus pins face miswiring, ground shifts and electrostatic discharge, which needs thick-oxide 5 V LDMOS and large ESD structures that mature 130 nm offers. Reach depends on edge timing, so slew is trimmed and delay budgeted. A dead bus must read as a known state."
   },
   "specs": {
    "title": "Edge timing and pin protection decide SKU-5, not the headline rate",
    "copy": "Read the 20 ns driver and 50 ns receiver delays, the −7 to +12 V RS-485 common mode and the ±15 kV protection target first; they set reach and survival. 20 Mbps and 1.2 km are two operating points. All are targets."
   },
   "questions": {
    "title": "ESD data and unit load decide if SKU-5 can drop into an old socket",
    "copy": "Silicon ESD data at ±15 kV, from a dedicated test chip, decides whether the pins survive a harness. Eighth-unit-load receivers decide whether 256 nodes fit one bus. The first pin-compatible target decides which discontinued interface part SKU-5 replaces first."
   },
   "fit": {
    "title": "SKU-5 sits at every bus node where interface parts face obsolescence",
    "copy": "It is the CAN-FD and RS-485 link at every node on a vehicle bus and on industrial buses, including harsh wiring harnesses. It gives SKU-9 its physical bus links and SKU-2 its wired meter bus. It offers a supply for interface parts facing obsolescence."
   },
   "evidence": {
    "title": "SKU-5’s line drivers are simulated; no pin has yet taken an ESD strike",
    "copy": "RTL is ready for the digital logic and the analog line drivers are designed and simulated (schematic and SPICE); layout and silicon proof follow on the prototype. No ESD, slew or unit-load figure has been measured, and ±15 kV needs a dedicated test chip."
   },
   "sources": {
    "title": "The SKU Blueprint sets SKU-5’s scope; this page corrects three annex figures",
    "copy": "The SKU Blueprint, October 2026, page 22, sets the scope, status and what the part replaces. Where Technical Annex v3, sheet 6, pairs 20 Mbps with 1.2 km, merges IEC 61000-4-2 with HBM, or quotes ±7 V common mode, this page gives the corrected form."
   },
   "close": {
    "title": "Bring your bus, its wiring and its ESD test, and we will scope SKU-5 for it",
    "copy": "Bring the protocol and data rate, cable length and node count, the common-mode range your ground shifts reach, the ESD test standard and level you must pass, and the discontinued part you want replaced. The reply names what SKU-5 must prove."
   }
  }
 },
 "sku6": {
  "id": "sku6",
  "headline": "SKU-6 ignores converter ripple and latches a real rail fault",
  "lead": "A supervisor must ignore the ripple a buck converter puts on a rail, yet catch a real brownout before memory corrupts, and hold its thresholds to a fraction of a percent across the military temperature range. Those demands pull against each other, so SKU-6 gives each of four rails its own trimmed sense chain and ends every confirmed fault at one latch.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "Each rail enters through its own matched divider",
    "body": "Four rails come in at VIN 1 to VIN 4: 5.0, 3.3, 1.8 and an adjustable 1.2/0.9 V, each behind 2 kV ESD protection. Each feeds its own Divider, a polysilicon ladder matched to 0.1%, so its Comparator sees a scaled copy of the rail whose ratio barely moves with temperature.",
    "zones": [
     "Sense chain · one per rail"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "Only a fault that outlasts 8 µs reaches the matrix",
    "body": "The chopper-stabilised Comparator holds its offset under 500 µV and adds 8 mV of hysteresis. Its output then passes the Deglitch counter, which drops anything shorter than 8 µs. Converter ripple dies there; a real brownout survives the window and reports a confirmed fault to the Fault matrix.",
    "zones": [
     "Sense chain · one per rail",
     "Fault logic"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "The matrix latches the fault and warns before it resets",
    "body": "The Fault matrix is maskable and latched, with a priority encoder and I²C registers that record which rail failed. It drives FAULT_N first, then RESET_N, an open-drain output held for a trimmed 200 ms. A latched fault stays asserted until it is cleared, so the system cannot miss it. MR / manual adds a push-button reset.",
    "zones": [
     "Fault logic",
     "Output stage"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "One trimmed bandgap sets every comparator threshold",
    "body": "Threshold accuracy starts in Reference + timebase. A curvature-corrected Bandgap at 1.20 V and 10 ppm/°C sets all four comparator thresholds, and a 5-bit OTP Trim brings it to ±0.5% once, at test. The Osc block supplies a 1 MHz timebase with a reference current, so the chip keeps its own time.",
    "zones": [
     "Reference + timebase",
     "Sense chain · one per rail"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "A late or early kick from the processor forces a reset",
    "body": "The Watchdog checks the processor, not the rails. Window logic opens and closes a window adjustable from 100 ms to 1.6 s, and firmware must kick WDI inside it. A kick that comes too early or never comes runs the Timeout counter out, which drives RESET_N in the Output stage, so a hung or runaway processor restarts.",
    "zones": [
     "Watchdog",
     "Output stage"
    ]
   }
  ],
  "closing": {
   "title": "None of these thresholds has been measured on silicon",
   "body": "SKU-6 is pre-silicon and every figure here is a design target, designed toward the MIL-STD-883K Class B screening flow. Four questions stay open: the deglitch window, the chopper’s own ripple, ladder ageing over twenty years, and what taking this part through screening first establishes."
  },
  "sections": {
   "physics": {
    "title": "Sub-percent thresholds and converter ripple decide SKU-6’s silicon.",
    "copy": "Thresholds held to a fraction of a percent across the military temperature range need chopper comparators, 0.1%-matched polysilicon and a 10 ppm/°C bandgap. Ripple that must not trip it, and a brownout that must, set the 8 µs deglitch before the latch."
   },
   "specs": {
    "title": "SKU-6 stands on a 500 µV offset, a 0.1% ladder and an 8 µs window.",
    "copy": "Comparator offset and ladder match decide whether a threshold is accurate; the deglitch window decides whether ripple is ignored. Rails, watchdog and reset timing follow from them. Every figure is a design target from the SKU Blueprint, October 2026, page 25, and the earlier annex sheet; none is measured."
   },
   "questions": {
    "title": "Four answers decide whether SKU-6’s 8 µs window is the right one.",
    "copy": "The deglitch and chopper answers decide whether a real fault is caught and converter noise is not. Ladder ageing decides whether thresholds hold for twenty years. The screening answer decides what every later DeepGrid part inherits from going first."
   },
   "fit": {
    "title": "SKU-6 sits on nearly every board, beside the PMIC and the safety MCU.",
    "copy": "It watches up to four rails so a board starts predictably below firmware, cross-checks the rails SKU-3 produces and holds SKU-4 in reset until power is good. The decision it changes: rail supervision and the processor watchdog come from one part."
   },
   "evidence": {
    "title": "SKU-6’s sensing chain runs on an FPGA; its analog half awaits silicon.",
    "copy": "The supervisor sensing chain runs as circuit code on an Artix-7 at 81.25 MHz, and the comparators and reference are designed and simulated. Layout and silicon proof follow on the December 2026 sky130 prototype, with production on SCL 180 nm; it is the first part into military screening."
   },
   "sources": {
    "title": "Three documents carry SKU-6’s targets, its FPGA proof and its job.",
    "copy": "The SKU Blueprint, October 2026, page 25, sets the job, status and screening plan. The Mature-Node Silicon whitepaper names the FPGA-validated sensing chain. Technical Annex v3, sheet 7, the earlier edition, states the original targets."
   },
   "close": {
    "title": "Bring your rails and converter noise; we will test SKU-6 against them.",
    "copy": "Send the rails and thresholds you supervise, your converter’s ripple, the shortest brownout that corrupts memory, the reset delay and watchdog window your processor needs, and the screening flow your platform requires."
   }
  }
 },
 "sku7": {
  "id": "sku7",
  "headline": "SKU-7 puts 77 GHz on SiGe and the target math on CMOS",
  "lead": "A 77 GHz radar needs transistor gain that standard CMOS lacks, a 4 GHz chirp that stays linear, and fast converters that must not leak digital noise into the receivers. One die cannot serve all three, so SKU-7 splits the work: a SiGe die sends and receives, a 130 nm CMOS die finds the targets, and the signal crosses between them once.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "A crystal, a PLL and a 38.5 GHz VCO shape the chirp",
    "body": "The chirp starts in Chirp synthesis + transmit on the SiGe die. A 40 MHz XTAL clocks the Ramp gen, which sets a sawtooth or triangle chirp profile. A fractional-N PLL with a 1 MHz loop bandwidth steers a 38.5 GHz VCO built on SiGe HBTs. The ramp must stay linear across the whole 4 GHz sweep, or the radar sees ghost targets.",
    "zones": [
     "Chirp synthesis + transmit · SiGe die"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "A doubler reaches 77 GHz and two PAs transmit",
    "body": "The × 2 block doubles the VCO to 77 GHz, so the oscillator runs at half the carrier. PA · TX1 and PA · TX2 each transmit at 13 dBm. The same × 2 output feeds the LO to every receive mixer, so transmit and receive share one chirp. A 4 GHz sweep in the 76 to 81 GHz band gives 3.75 cm range resolution.",
    "zones": [
     "Chirp synthesis + transmit · SiGe die"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "Four receive channels mix each echo down to IF",
    "body": "Echoes return to the Receive array, four identical channels on the SiGe die. LNA × 4 amplifies each at a 3.5 dB noise figure, Mixer × 4 mixes it with the LO, IF amp × 4 lifts it, and AAF × 4 filters it at 10 MHz. The beat frequency carries range; the phase across the four receivers carries the angle of arrival.",
    "zones": [
     "Receive array · 4 channels · SiGe die"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "The IF signals cross the die boundary once",
    "body": "This is the only die crossing. The four IF signals leave the SiGe die for ADC × 4 in Signal processing on the CMOS die: four 12-bit converters at 40 MSPS. Windowing applies Hann or Blackman, a 1024-point radix-4 Range FFT takes 26 µs per chirp, and a 128-point Doppler FFT across chirps fills the Range-Doppler map in 512 KB of SRAM.",
    "zones": [
     "Receive array · 4 channels · SiGe die",
     "Signal processing · CMOS die"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "CFAR and beamforming turn the map into detections",
    "body": "The Range-Doppler map feeds Detection + output on the CMOS die. Cell-averaging CFAR holds a constant false-alarm rate against the background clutter, and Angle est uses digital beamforming across the four receivers to resolve angle to 15°. Each detection now carries range, velocity and angle.",
    "zones": [
     "Signal processing · CMOS die",
     "Detection + output · CMOS die"
    ]
   },
   {
    "marks": [
     "⑥"
    ],
    "title": "Up to 64 tracked targets leave for the vehicle ECU",
    "body": "The Target list holds range, velocity, angle and RCS for up to 64 tracks per frame. It leaves the package for the ECU over CAN-FD, 100BASE-T1 or MIPI CSI-2. Everything before this point stays inside the two dies, so the host system receives targets rather than raw radar samples.",
    "zones": [
     "Detection + output · CMOS die"
    ]
   }
  ],
  "closing": {
   "title": "The SiGe front end can only be proven on silicon",
   "body": "SKU-7 is pre-silicon and every figure is a design target, designed toward ISO 26262 ASIL-B, DO-160G and MIL-STD-883K. The front end has no FPGA stand-in. Open questions: the die boundary, chirp error under 50 kHz rms, risk across IHP wafer runs, and co-existence with nearby radios."
  },
  "sections": {
   "physics": {
    "title": "77 GHz gain puts SKU-7’s front end on SiGe and its FFTs on CMOS.",
    "copy": "Standard CMOS lacks the gain at 77 GHz, so the front end uses SiGe transistors with fT above 350 GHz. A 4 GHz linear chirp sets 3.75 cm resolution. Fast converters would inject noise beside the receivers, so they sit across a package boundary."
   },
   "specs": {
    "title": "The 4 GHz sweep and the 2 × 4 array set what SKU-7 can resolve.",
    "copy": "The sweep sets range resolution, two transmit and four receive channels set angle, and four 12-bit 40 MSPS converters set what reaches the FFTs. fT is transistor capability, not radar frequency. Every figure is a design target from the SKU Blueprint, October 2026, page 28, and the earlier annex sheet."
   },
   "questions": {
    "title": "SKU-7’s open risks sit at the die boundary and in the chirp ramp.",
    "copy": "The die-boundary and chirp-linearity answers decide whether the radar sees real targets or ghosts. The silicon-risk answer decides how many IHP wafer runs the front end needs. Co-existence decides whether it can share a mast with UHF and VHF radios."
   },
   "fit": {
    "title": "SKU-7 hands tracked targets, not raw samples, to the vehicle or mast.",
    "copy": "It goes into DeepGrid’s truck mirror-tower radar, automotive emergency braking, and defence perimeter and counter-drone radar, feeding SKU-9 or D100. The decision it changes: the host receives up to 64 tracked targets over CAN-FD, 100BASE-T1 or MIPI CSI-2."
   },
   "evidence": {
    "title": "SKU-7 is RTL-ready on CMOS; its SiGe front end waits for a 2027 IHP run.",
    "copy": "RTL for the CMOS signal-processing chip is ready and validated on FPGA. The SiGe front end has no FPGA equivalent and is still to be designed; it is proven only on an IHP SG13G2 run, planned for 2027. No die has been fabricated or measured."
   },
   "sources": {
    "title": "Compendium §3.3 explains why SKU-7’s RF and baseband split dies.",
    "copy": "The SKU Blueprint, October 2026, page 28, sets the bands, status and what the part replaces. Technical Annex v3, sheet 8, the earlier edition, gives the RF targets, and the SKU Architecture Compendium, §3.3, explains the two-die split and what fT does and does not mean."
   },
   "close": {
    "title": "Bring your platform and its range needs; we will scope SKU-7 against them.",
    "copy": "Send the range resolution and target count you need, the vehicle, mast or drone it mounts on, the radios beside it, the interface your host expects, and the safety and environmental standards your platform must meet."
   }
  }
 },
 "sku8": {
  "id": "sku8",
  "headline": "SKU-8 drives a cockpit panel and flags a frozen picture in two frames",
  "lead": "A rugged display needs two kinds of silicon at once: dense timing and pixel processing, and column outputs that swing 0 to 12 V. A picture that silently stops updating is a hazard, and contrast that fades at +85 °C in direct sun is a failure. SKU-8 is a timing chip and its high-voltage column drivers, priced as one chipset, checking every frame in hardware; the cockpit version is the same chip over a wider temperature range.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "Video enters over LVDS or MIPI DSI into a line buffer",
    "body": "A frame arrives at Video input through LVDS RX, a dual link at 655 Mbps per lane, through four-lane DSI RX, or as parallel RGB. Both receivers write the Line buffer, dual-port SRAM holding four lines of 1280 pixels at 24 bits, which decouples the incoming link from the pace of the pixel pipeline.",
    "zones": [
     "Video input"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "The pipeline corrects every pixel for panel temperature",
    "body": "The Line buffer feeds the Pixel pipeline at 24 bits per pixel. De-gamma linearises the input, Colour applies a 3 × 3 matrix with white point, and the Gamma LUT maps it through a 14-bit table with temperature feedback from an on-die sensor. LCD response shifts with heat, and this is how contrast holds at +85 °C in direct sun.",
    "zones": [
     "Video input",
     "Pixel pipeline"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "Dithered pixels set one 10-bit DAC per column",
    "body": "Dither applies temporal and spatial dithering, then the pixels cross the control bus to the Column (source) drivers. The DAC bank holds one 10-bit resistor-string DAC with a buffer for each column, 1280 in all. Here the digital half of the die hands over to the high-voltage half.",
    "zones": [
     "Pixel pipeline",
     "Column (source) drivers · high-voltage"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "High-voltage amps swing 3,840 outputs from 0 to 12 V",
    "body": "Output amps are rail-to-rail high-voltage amplifiers on thick oxide, swinging 0 to 12 V, a range dense nodes cannot reach. They drive Column outputs × 1280: three sub-pixels per column, 3,840 outputs. Charge-sharing precharge between adjacent columns cuts drive power by about 40%.",
    "zones": [
     "Column (source) drivers · high-voltage"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "The timing controller scans the rows at up to 24 V",
    "body": "Timing + test sets the frame. The TCON generates horizontal and vertical timing with programmable porches from a 100 MHz pixel-clock PLL, and scans the rows through the Gate driver IF in Row + backlight with a level shift up to 24 V. VCOM drives the common electrode, and Backlight runs the LED string across eight local-dimming zones.",
    "zones": [
     "Timing + test",
     "Row + backlight"
    ]
   },
   {
    "marks": [],
    "title": "Hardware notices a frozen picture within two frames",
    "body": "BIST + safety in Timing + test compares a CRC of each frame with the one before, in hardware. If the image stops updating, it alerts the operator within two frames instead of leaving a stale picture on a cockpit screen. Test pattern adds colour bars for checking the drive path to the panel.",
    "zones": [
     "Timing + test"
    ]
   }
  ],
  "closing": {
   "title": "No frame has been driven on SKU-8 silicon yet",
   "body": "SKU-8 is pre-silicon and every figure is a design target, designed toward ISO 26262 ASIL-B, MIL-STD-810G and DEF-STAN 00-35. Open questions: which voltages force the high-voltage process, how much energy precharge recovers, how frame CRCs alert within two frames, and how gamma holds contrast at +85 °C."
  },
  "sections": {
   "physics": {
    "title": "12 V columns and 24 V rows keep SKU-8 off dense digital nodes.",
    "copy": "Column swings of 0 to 12 V and a 24 V gate level shift need thick-oxide amplifiers on 130 nm high-voltage CMOS. Sunlight at +85 °C needs temperature-fed gamma, and a frozen cockpit picture needs a frame CRC in hardware."
   },
   "specs": {
    "title": "SKU-8 is judged on its 0 to 12 V swing, 14-bit gamma and freeze alert.",
    "copy": "The column swing, the temperature-fed 14-bit gamma and the two-frame freeze alert are what a rugged-display evaluation turns on; resolution and inputs follow the panel. Every figure is a design target from the SKU Blueprint, October 2026, page 31, and the earlier annex sheet; none is measured."
   },
   "questions": {
    "title": "SKU-8’s answers decide whether a crew can trust what it sees.",
    "copy": "The freeze-detection answer decides whether a stale picture is caught before the crew acts on it. Heat and contrast decide readability at +85 °C. The process and charge-sharing answers decide drive voltage and how much power 1280 columns draw."
   },
   "fit": {
    "title": "SKU-8 replaces an imported timing controller and source driver pair.",
    "copy": "It drives rugged and industrial displays, control panels, rail passenger displays and, in its wider-temperature version, cockpit displays, with SKU-3 generating its bias rails and SKU-9 feeding it graphics in a vehicle. The decision it changes: timing, column drive and freeze detection come as one chipset."
   },
   "evidence": {
    "title": "SKU-8’s column amplifiers are simulated; layout follows on the prototype.",
    "copy": "RTL is ready for the digital logic (video input, colour, timing controller), and the high-voltage column amplifiers are designed and simulated. Layout and silicon proof follow on the December 2026 prototype. No panel has been driven and no freeze alert timed; the 40% precharge saving and +85 °C contrast are design targets."
   },
   "sources": {
    "title": "The SKU Blueprint, page 31, scopes SKU-8 to rugged panels.",
    "copy": "The SKU Blueprint, October 2026, page 31, sets the scope, status and what the part replaces. Technical Annex v3, sheet 9, the earlier edition, gives the drive targets, and the SKU Architecture Compendium sets the limit on rugged-display claims."
   },
   "close": {
    "title": "Bring your panel and its sunlight; we will say what SKU-8 must prove.",
    "copy": "Send the panel resolution and column voltage, the gate-driver voltage, the video interface, the temperature and sunlight envelope, how fast a frozen picture must be flagged, and the environmental standards your display must meet."
   }
  }
 },
 "sku9": {
  "id": "sku9",
  "headline": "SKU-9 turns vehicle network traffic into switched power in one zone",
  "lead": "A vehicle zone today is a relay box and point-to-point wiring. Replacing it puts brake-by-wire messages, comfort traffic, 12 V and 48 V switching, safety and security on one chip, so latency must stay bounded and functions must stay isolated. SKU-9 owns that zonal edge on 130 nm; the central computer is a sub-10 nm part and is not claimed.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "Messages arrive on Ethernet, CAN, LIN and FlexRay",
    "body": "Traffic enters at In-vehicle network · gateway: 100BASE-T1 × 2 for automotive Ethernet, CAN-FD × 8, CAN-XL × 1, LIN × 8 masters and FlexRay × 1. The gateway routes and rate-limits between domains, so a flood on one bus cannot starve another. Every port lands on the AXI4 crossbar, in a 130 nm chip at 100 MHz.",
    "zones": [
     "In-vehicle network · gateway"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "The TSN switch schedules traffic against precision time",
    "body": "In Real-time control, the TSN switch applies an 802.1Qbv time-aware shaper, and PTP keeps an 802.1AS clock in sub-µs sync. Brake-by-wire messages get reserved time slots on a shared link while bulk data waits its turn. Bounded latency is designed into hardware rather than left to software scheduling.",
    "zones": [
     "Real-time control"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "The service router forwards each message across the crossbar",
    "body": "The Service router handles SOME/IP and DoIP, turning network messages into service calls and diagnostics. It forwards each one across the AXI4 crossbar to the block that owns the action: the safety island, the security module or the zone’s power outputs. One crossbar carries every path, which is why isolation matters.",
    "zones": [
     "Real-time control"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "Sixteen smart fuses replace the relay box at the loads",
    "body": "Commands reach Zonal power + I/O and become switched power. Smart fuse × 16 pairs an eFuse with sensing and a programmable I²t trip, replacing the relay box. HS driver × 8 handles load control, PWM × 12 drives actuators, and a 12-bit ADC senses 24 channels. BCD power devices sit beside the logic to switch 12 V and 48 V loads.",
    "zones": [
     "Zonal power + I/O"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "A lockstep mismatch drives the zone to its safe state",
    "body": "The Safety island runs DGridRiscV × 2 in lockstep with a two-cycle skew, protected by PMP and ECC. The Comparator checks bus and retire outputs, and a mismatch drives the safe state. Freedom from interference, an MPU plus a bus firewall, keeps comfort functions such as lighting away from safety-critical registers.",
    "zones": [
     "Safety island"
    ]
   },
   {
    "marks": [],
    "title": "A security module checks every image before it runs",
    "body": "Security sits across the same paths. The HSM provides AES-256, ECC-256 and a true RNG. Secure boot starts from a root of trust in an OTP key store with A/B slots, and the OTA engine verifies each signed image and rolls back when one fails, so a bad update never replaces the working bank.",
    "zones": [
     "Security"
    ]
   }
  ],
  "closing": {
   "title": "ASIL-D is a design target here, not a certificate",
   "body": "SKU-9 is pre-silicon and every figure is a design target, designed toward ISO 26262 ASIL-D, EVITA Full, AUTOSAR Classic 4.4 and AEC-Q100 Grade 1. Open questions: where the node line falls, under 10 µs for brake-by-wire, smart-fuse cut-off without avalanche damage, and isolation rules."
  },
  "sections": {
   "physics": {
    "title": "One zone chip must bound brake latency and wall lighting off steering.",
    "copy": "Switching 12 V and 48 V harness loads needs BCD power devices beside the logic. Brake-by-wire on a shared link needs a time-aware shaper and precision time sync in hardware. Safety and comfort on one die need a lockstep island and bus firewalls."
   },
   "specs": {
    "title": "Sixteen smart fuses and a TSN switch carry SKU-9’s case.",
    "copy": "The TSN switch, the port mix, the sixteen I²t smart fuses and the two-cycle lockstep island decide whether one chip can replace a relay box; central compute is out of scope. Every figure is a design target from the SKU Blueprint, October 2026, page 34, and the earlier annex sheet."
   },
   "questions": {
    "title": "SKU-9’s answers decide whether brake and comfort traffic can share it.",
    "copy": "The latency answer decides whether brake-by-wire can share a port with bulk data under 10 µs. Isolation decides whether lighting can reach steering. Solid-state fusing decides whether the relay box goes. The node line decides what stays off this chip."
   },
   "fit": {
    "title": "SKU-9 takes over the relay box; the central computer stays elsewhere.",
    "copy": "It sits in each zone of a software-defined vehicle, beside SKU-5 transceivers on the buses and SKU-7 radar feeding target data, reusing SKU-4’s lockstep pattern. The decision it changes: whether a zone’s relay box and point-to-point wiring become one networked, fused chip."
   },
   "evidence": {
    "title": "SKU-9 is RTL-ready, with its prototype on the December 2026 shuttle.",
    "copy": "RTL is ready and the prototype is on the December 2026 shuttle, a 130 nm chip at 100 MHz for the zonal layer. No die, harness-weight reduction or qualified vehicle implementation is claimed. The annex labelled the safety island ASIL-D, but no certificate exists for any DeepGrid part, so ASIL-D is a design target."
   },
   "sources": {
    "title": "The SKU Blueprint, page 34, sets SKU-9’s clock and scope.",
    "copy": "The SKU Blueprint, October 2026, page 34, sets the 100 MHz clock, status and scope. Technical Annex v3, sheet 10, the earlier edition, gives the ports and fuses, including the ASIL-D wording this page corrects."
   },
   "close": {
    "title": "Bring your zone’s loads and buses; we will test SKU-9’s latency against them.",
    "copy": "Send the zone’s loads and their 12 V or 48 V currents, the buses and port counts, the latency your brake-by-wire messages need, the safety target, and the security and update requirements your vehicle platform sets."
   }
  }
 },
 "d100": {
  "id": "d100",
  "headline": "D100’s failsafe can land the drone without its own flight computer",
  "lead": "A software failsafe runs on the computer it is meant to rescue, so when the flight stack hangs, the recovery hangs with it. GPS can be denied, so navigation needs a second source. D100 answers both in hardware: a geometric pose engine that needs no GPS, and an isolated failsafe island with its own power, clock and path to the motor controllers.",
  "beats": [
   {
    "marks": [
     "①"
    ],
    "title": "Sensors and the RC link reach two flight cores",
    "body": "Flight control · hard real-time starts with IMU / MAG / BARO over three SPI links at 8 kHz, plus RC + telemetry over SBUS, CRSF or MAVLink. Both reach DGridRiscV × 2: one core for flight control and one for navigation, running the PX4 or ArduPilot loop in hard real time.",
    "zones": [
     "Flight control · hard real-time"
    ]
   },
   {
    "marks": [
     "②"
    ],
    "title": "Cameras feed a pose engine that needs no GPS",
    "body": "In Visual-inertial odometry, frames enter MIPI CSI-2 on two lanes at up to 1080p60. The ISP rectifies them and corrects lens shading, and Feature extracts FAST corners with BRIEF descriptors, about 2k points per frame. The Pose engine is geometry, not learned perception, so it needs neither GPS nor trained weights.",
    "zones": [
     "Visual-inertial odometry"
    ]
   },
   {
    "marks": [
     "③"
    ],
    "title": "A 30 Hz pose reaches the flight loop over the crossbar",
    "body": "The Pose engine fuses features with the IMU in an EKF with IMU pre-integration and sliding-window bundle adjustment, producing a six-degree-of-freedom pose at 30 Hz. It crosses the 128-bit AXI4 crossbar to the flight cores. In phase 2 the NPU, with attention and softmax in hardware, adds object detection on the same 28 nm chip.",
    "zones": [
     "Visual-inertial odometry",
     "Flight control · hard real-time",
     "AI · phase 2 · on the 28 nm chip"
    ]
   },
   {
    "marks": [
     "④"
    ],
    "title": "In normal flight, motor commands leave on ESC OUT",
    "body": "The flight loop combines attitude, pilot input and pose into motor commands. ESC OUT sends them as DShot600 on eight channels to the external ESCs and motors. This normal path depends on the flight cores running correctly, and that is exactly what the failsafe path does not assume.",
    "zones": [
     "Flight control · hard real-time"
    ]
   },
   {
    "marks": [
     "⑤"
    ],
    "title": "The link monitor trips the safe state in hardware",
    "body": "The Failsafe island runs on isolated power and clock and watches from outside the mission stack. Its Link monitor detects RC loss, GPS loss or an IMU fault in hardware, not firmware. A trip drives the Safe-state FSM, which selects return to home or land, and the island keeps running when the flight software is what failed.",
    "zones": [
     "Failsafe island · isolated power and clock"
    ]
   },
   {
    "marks": [
     "F"
    ],
    "title": "The independent path takes the ESCs on its own",
    "body": "The Independent path drives the ESCs directly, bypassing the flight cores, the odometry and the AI. Recovery does not wait on the computer it is meant to rescue. This establishes a structure, not a result: the architecture does not establish jamming immunity or certified flight safety.",
    "zones": [
     "Failsafe island · isolated power and clock"
    ]
   }
  ],
  "closing": {
   "title": "No D100 silicon has been fabricated or measured",
   "body": "D100 is pre-silicon. An Artix-7 FPGA at 81.25 MHz validates the design; every figure is a target, designed toward the DGCA type certification path, STANAG 4586 and MIL-STD-810H. Open questions: what the failsafe must see, drift under jamming, heat at +55 °C, and crossbar timing."
  },
  "sections": {
   "physics": {
    "title": "D100’s recovery needs power and a clock the flight stack cannot hang.",
    "copy": "Recovery must work after the flight software fails, so the safe-state machine has its own power, clock and wiring to the ESCs, and can be built at 130 nm. Navigation without GPS needs a hardware 30 Hz pose engine. Vision and AI need the density only a 28 nm chip delivers."
   },
   "specs": {
    "title": "D100 stands on its isolated failsafe and its 30 Hz pose engine.",
    "copy": "The failsafe’s isolated power, clock and ESC link, and the six-DoF pose at 30 Hz, decide whether the airframe recovers and navigates without GPS. The 10 TOPS accelerator is phase 2. Every figure is a design target from the SKU Blueprint, October 2026, page 43, and the earlier annex sheet."
   },
   "questions": {
    "title": "D100’s answers decide when the island acts and how far it drifts.",
    "copy": "The failsafe answer decides what the island must see before it takes the motors. The drift answer decides whether GPS-denied navigation holds under jamming. Thermal decides the closed-fuselage envelope at +55 °C; the two-node answer decides whether the 130 nm failsafe island stays isolated from the 28 nm chip."
   },
   "fit": {
    "title": "D100 gives a drone a recovery path its mission stack cannot take down.",
    "copy": "It goes into drones as flight control and visual-inertial navigation, driving SKU-1 motors, with SKU-7 radar for collision avoidance and SKU-4’s lockstep pattern in its cores. The decision it changes: the failsafe becomes hardware wired to the ESCs, not a software task."
   },
   "evidence": {
    "title": "D100’s pose engine runs on an FPGA; its failsafe has no silicon yet.",
    "copy": "The drone position engine runs as circuit code on an Artix-7 at 81.25 MHz. No D100 die has been fabricated. Track B is scoped and funded separately from the eleven SKUs. The architecture establishes neither jamming immunity nor certified flight safety."
   },
   "sources": {
    "title": "Compendium §3.4 sets D100’s die split; the whitepaper, its FPGA proof.",
    "copy": "The SKU Blueprint, October 2026, page 43, sets D100 as a 28 nm Track B chip with a 130 nm failsafe island, funded by a separate round. Technical Annex v3, sheet 11, the earlier edition, gives the flight-control targets. The Mature-Node Silicon whitepaper names the FPGA-validated position engine."
   },
   "close": {
    "title": "Bring your airframe and its failure cases; we will scope D100’s failsafe for it.",
    "copy": "Send the airframe and its ESCs, what must trigger a safe state and what that state is, how long GPS may be denied, the camera and thermal envelope, and the certification path your programme follows."
   }
  }
 }
};
