'use client';
import {useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {url} from './routes';
const families=[
 {name:'Motor control',code:'SKU-1',file:'sku-1',w:1513,h:885,copy:'The control engine and the power stage, in one architecture.'},
 {name:'Power management',code:'SKU-3',file:'sku-3',w:1513,h:903,copy:'Convert the equipment power bus into sequenced board supplies.'},
 {name:'Radar sensing',code:'SKU-7',file:'sku-7',w:1513,h:763,copy:'A specialist RF front end, sampling and baseband processing.'},
 {name:'Drone integration',code:'D100',file:'d100',w:1553,h:945,copy:'Separate flight safety from higher-level perception compute.'},
];
export function DeepGridVisual({kind,priority=false}:{kind:'overview'|'products'|'technology';priority?:boolean}){
 const [selected,setSelected]=useState(0);const p=families[selected];
 if(kind==='products')return <figure className="v11-visual v11-visual-products"><div className="v11-family-tabs" role="group" aria-label="Explore product architecture diagrams">{families.map((x,i)=><button key={x.code} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{x.name}<span>{x.code}</span></button>)}</div><a href={url('/products/'+p.file)} aria-label={'Explore '+p.code+' '+p.name}><img src={url('/diagrams/'+p.file+'-architecture.svg')} alt={p.code+' '+p.name+' original DeepGrid architecture diagram'} width={p.w} height={p.h} loading={priority?'eager':'lazy'} decoding="async"/></a><figcaption><strong>{p.code} · {p.copy}</strong><br/>Original DeepGrid architecture diagram · pre-silicon design. <a href={url('/products/'+p.file)}>Explore this part <ArrowUpRight size={14}/></a></figcaption></figure>;
 if(kind==='overview')return <figure className="v11-visual v11-visual-overview"><a href={url('/products')} aria-label="Explore the silicon portfolio"><img src={url('/images/dgs/home-hero.webp')} srcSet={`${url('/images/dgs/home-hero-768.webp')} 768w, ${url('/images/dgs/home-hero.webp')} 1536w`} sizes="100vw" alt="Concept render of a chip package seated on a circuit board, blue light running along the traces from its edges" width={1536} height={1024} fetchPriority="high" loading="eager" decoding="async"/></a><figcaption><strong>DeepGrid mature-node silicon · concept render</strong><br/>Illustrative portfolio visual, not a product photograph. <a href={url('/products')}>Explore the portfolio <ArrowUpRight size={14}/></a></figcaption></figure>;
 return <figure className="v11-visual v11-visual-technology"><a href={url('/images/v11/dg32-lite-architecture.svg')} target="_blank" rel="noreferrer" aria-label="Open full-size DG32-LITE architecture diagram"><img src={url('/images/v11/dg32-lite-architecture.svg')} width={1518} height={1045} alt="Original DG32-LITE system architecture: paired MAIN and CHECKER cores, fault latch, memory, control datapath and external gate driver" loading={priority?'eager':'lazy'} decoding="async"/></a><dl className="v11-tech-labels"><div><dt>Execute. Check. Compare.</dt><dd>MAIN and CHECKER execute with a two-cycle skew. A comparator observes disagreement.</dd></div><div><dt>A hardware fault path.</dt><dd>A sticky latch records the mismatch. FAULT_N disables the external gate driver.</dd></div><div><dt>Control has its own datapath.</dt><dd>ADC acquisition, CORDIC and PWM use dedicated hardware. Firmware runs the d/q PI regulators.</dd></div></dl><figcaption>Original DG32-LITE architecture diagram from the DeepGrid architecture package. Pre-silicon design; open the image for the complete diagram.</figcaption></figure>;
}
