/** Reading notes for every architecture diagram on the site: what each zone of the drawing is, why
 *  it exists, what the numbered markers mean, and where to read further.
 *
 *  Zone and marker copy is taken from the architecture guide that ships beside each diagram
 *  (public/downloads/dg32-*-architecture-guide.md); `section` is that guide's heading, so each note
 *  opens the guide at the paragraph it summarises. Add no figure here that the guide does not carry.
 *
 *  Background references explain the general technique a block uses. They are reading, not evidence:
 *  none of them describes DG32, and none implies DG32 shares those parts' certifications. Every URL
 *  was opened and checked on 2026-10-02. */
import {readHref} from './doc-links';
import {url} from './routes';
import {skuDiagrams} from './sku-diagram-notes';

/** Keep a number with its unit on one line ("114 MHz", "2 A", "64 KB"), as the rest of the site's copy does. */
const UNIT = /(\d) (?=(?:MHz|kHz|GHz|Gbps|Mbps|kSPS|MSPS|KB|MB|GB|TOPS|mA|µA|µs|ns|ms|µW|mV|kV|dBm|dB|ppm|°C|bit|V|A|s|cycles|pages|keys|lanes|channels|outputs|columns|zones|nodes|domains)\b)/g;
export const nbspUnits = (s: string) => s.replace(UNIT, '$1\u00a0');

/** A native architecture diagram, rendered in the site's own design: rows of zones of blocks, with the
 *  numbered markers of the reading path on the blocks they refer to. Generated by scripts/sku-diagrams/. */
export type NativeBlock = {k?: string; t: string; s?: string; span?: number; marks?: string[]};
export type NativeZone = {k?: string; name: string; cols: number; mcols?: number; w: number; tone?: 'safe' | 'optional'; note?: string; blocks: (NativeBlock | null)[]};
export type NativeRow = {bus: string; k?: string} | {zones: NativeZone[]};
export type NativeDiagramData = {frame: string; rows: NativeRow[]; edges?: {a: string; b: string; m?: string; d?: string}[]; input?: string; output?: string; banner?: string; strip?: string[]};

export type DiagramZone = {name: string; what: string; why?: string; section: string};
export type DiagramMarker = {mark: string; text: string};
export type DiagramRef = {title: string; note: string; href: string; meta?: string};
export type DiagramNotes = {
  guide: string;
  zones: DiagramZone[];
  markers: DiagramMarker[];
  primary: DiagramRef[];
  background: DiagramRef[];
};

const DOCS = '/downloads/docs/';
const LITE_GUIDE = '/downloads/dg32-lite-architecture-guide.md';
const DOM_GUIDE = '/downloads/dg32-2dom-architecture-guide.md';
const D100_GUIDE = '/downloads/d100-architecture-guide.md';

const DSHOT: DiagramRef = {
  title: 'DShot and bidirectional DShot',
  note: 'The digital ESC protocol the DShot channels speak.',
  href: 'https://brushlesswhoop.com/dshot-and-bidirectional-dshot/',
  meta: 'Explainer',
};

const AMBA: DiagramRef = {
  title: 'Arm AMBA specifications, including AXI',
  note: 'The bus protocol family the on-chip bus and the engine bridges are modelled on.',
  href: 'https://www.arm.com/architecture/system-architectures/amba/amba-specifications',
  meta: 'Arm',
};

export const diagramNotes: Record<'lite' | '2dom' | 'd100', DiagramNotes> = {
  lite: {
    guide: LITE_GUIDE,
    zones: [
      {name: 'Safety core', section: 'Component: Safety core',
        what: 'MAIN runs the application. CHECKER runs the same instructions two cycles later on identical inputs, the comparator checks every committed store, and the fault latch holds the first cause and drives FAULT_N.',
        why: 'A silent datapath fault produces a wrong PWM edge, and a wrong edge can destroy a bridge.'},
      {name: 'Memory and boot', section: 'Component: Memory and boot',
        what: 'The 64 KB mask ROM validates the flash image, copies it into 32 KB of dual-port SRAM and jumps to it. One SRAM port serves data, the other instruction fetch.',
        why: 'The die has no management core and no debugger halt, so the boot path must start the chip on its own.'},
      {name: 'Supervision', section: 'Component: Safety core',
        what: 'The windowed watchdog faults a kick that arrives too early or too late. The interrupt controller delivers 16 sources identically to both cores.',
        why: 'Identical delivery is what keeps CHECKER in step when firmware branches on an interrupt or a peripheral read.'},
      {name: 'On-chip bus', section: 'Component: Bus, system and test',
        what: 'Two masters, the CPU first and the DMA second, with single-outstanding, deterministic latency. An unmapped or disabled address completes with a bus error.',
        why: 'On a chip with no debugger, a hung bus would be a brick.'},
      {name: 'Motor drive', section: 'Component: Motor drive',
        what: 'Centre-aligned complementary PWM on six gate pins with dead-time, and a hardware brake that forces all six outputs off within two clock cycles. Four DShot channels share the PWM pads.',
        why: 'Gate timing and the safe state are too important to leave to a firmware loop.'},
      {name: 'Sensing and math', section: 'Component: Sensing and math',
        what: 'Encoder and Hall decode with edge timestamps, an 8-bit differential SAR ADC fired by the PWM, and a CORDIC for sin, cos and atan2 at a fixed cost per operation.',
        why: 'The CPU core is fetch-bound at about 8 cycles per instruction, so the expensive parts of the loop are hardware.'},
      {name: 'Connectivity and test', section: 'Component: Connectivity',
        what: 'Two UARTs, an SPI master, an I²C master and GPIO with atomic set and clear. JTAG and internal scan chains serve production test.'},
      {name: 'Off-chip', section: 'Power-on boot',
        what: 'QSPI NOR flash holds the application image. The gate driver and three-phase bridge, the motor sensors and the host sit outside the package.'},
    ],
    markers: [
      {mark: '①', text: 'The PWM period centre fires the ADC sample, where current ripple is lowest.'},
      {mark: '②', text: 'Phase current goes to the CORDIC, which runs the Clarke and Park transforms with the rotor angle.'},
      {mark: '③', text: 'The transformed currents go to the CPU, which runs the d and q PI regulators in plain C.'},
      {mark: '④', text: 'The PI output sets the PWM duty in shadow registers that load at the next period boundary.'},
      {mark: '⑤', text: 'Gate signals leave for the external gate driver.'},
      {mark: 'F', text: 'FAULT_N from the fault latch turns the bridge off in hardware, without firmware.'},
    ],
    primary: [
      {title: 'DG32-LITE architecture guide', note: 'Every block, the three data flows, timing headroom and the locked decisions.', href: readHref(LITE_GUIDE), meta: 'Opens in the site'},
      {title: 'DG32-LITE preliminary datasheet', note: 'Pin, electrical and peripheral detail for the part.', href: url(DOCS + 'deepgrid-dg32-lite-preliminary-datasheet.pdf'), meta: 'PDF · 12 pages'},
      {title: 'DG32 QFN-64 datasheets, both parts', note: 'DG32-LITE and DG32-2DOM in one document.', href: url(DOCS + 'deepgrid-datasheets-qfn64.pdf'), meta: 'PDF · 24 pages'},
      {title: 'Architecture deck and narrated film', note: 'The same diagram walked through slide by slide.', href: url('/resources') + '?pkg=lite', meta: 'Deck · film'},
    ],
    background: [
      {title: 'Hercules safety MCUs (TI SPRY178)', note: 'How a checker CPU fed the same inputs, offset by 1.5 or 2 cycles, catches faults; also why a watchdog should be windowed.', href: 'https://www.ti.com/lit/fs/spry178/spry178.pdf', meta: 'Texas Instruments · PDF'},
      {title: 'Field Orientated Control of 3-Phase AC-Motors (TI BPRA073)', note: 'The Clarke and Park transforms, the PI regulator and space-vector PWM behind markers ① to ④.', href: 'https://www.ti.com/lit/an/bpra073/bpra073.pdf', meta: 'Texas Instruments · PDF'},
      {title: 'The CORDIC trigonometric computing technique', note: 'Volder, IRE Transactions on Electronic Computers, 1959: the shift-and-add method the CORDIC block uses.', href: 'https://doi.org/10.1109/TEC.1959.5222693', meta: 'IEEE · DOI'},
      {title: 'RISC-V ratified specifications', note: 'The RV32IM instruction set both cores execute.', href: 'https://riscv.org/specifications/ratified/', meta: 'RISC-V International'},
      AMBA,
      DSHOT,
      {title: 'SkyWater SKY130 PDK documentation', note: 'The open 130 nm process the datasheet names.', href: 'https://skywater-pdk.readthedocs.io/en/main/', meta: 'SkyWater · Google'},
    ],
  },
  '2dom': {
    guide: DOM_GUIDE,
    zones: [
      {name: '50 MHz control domain', section: 'Component: Shared base (identical to DG32-LITE)',
        what: 'Everything in DG32-LITE: the lockstep CPU pair, fault latch and supervision, boot ROM and SRAM, motor drive, sensing and math, connectivity and test.',
        why: 'The control core is closed and hardened. Reopening it to add the engine would risk the one part of the chip that must be right, so the engine is an addition only.'},
      {name: 'Clock-domain bridges', section: 'Component: Clock-domain bridges',
        what: 'A lite bridge for programming, one transaction at a time, and burst read and burst write bridges that each move a whole burst in one crossing, through a four-phase request and acknowledge over two-flop synchronisers.',
        why: 'Crossings are rare, because keys and values load once and outputs write back once, so a small, provably safe handshake beats a FIFO with gray-coded pointers.'},
      {name: '114 MHz attention engine', section: 'Component: INT8 attention engine',
        what: 'Six stages per query row: program the shapes, multiply QKᵀ on a 16-lane array, weight through the softmax EXP table, combine with one reciprocal per row, requantise to INT8, write back.',
        why: 'Condition monitoring needs matrix math that a fetch-bound CPU core cannot run without starving the control loop.'},
      {name: 'K and V buffers, EXP table', section: 'Component: Key/value buffers',
        what: 'Keys and values sit on SRAM macros next to the engine, loaded once per kick and re-read for every query row. The EXP table holds 256 15-bit weights.',
        why: 'Loading once keeps per-head bus traffic around 1% of occupancy, so the engine does not fight the rest of the die for memory.'},
      {name: 'DMA and interrupts', section: 'Component: Key/value buffers',
        what: 'The DMA can feed the engine from the SRAM’s idle second read port, and the engine’s done interrupt reaches both lockstep cores.'},
    ],
    markers: [
      {mark: '①', text: 'Firmware on the lockstep CPU programs the shapes through the lite bridge, then sets start.'},
      {mark: '②', text: 'Keys, values and the EXP table load once through the burst read bridge.'},
      {mark: '③', text: 'The INT8 output writes back to memory through the burst write bridge.'},
      {mark: '④', text: 'The engine raises done; the interrupt controller delivers it to both cores. A later kick can reuse the resident keys and values.'},
    ],
    primary: [
      {title: 'DG32-2DOM architecture guide', note: 'The engine pipeline, buffers, bridges, timing and the four design decisions.', href: readHref(DOM_GUIDE), meta: 'Opens in the site'},
      {title: 'DG32-2DOM system architecture: block definition', note: 'Per-block architecture of the attention variant.', href: url(DOCS + 'deepgrid-dg32-2dom-system-architecture.pdf'), meta: 'PDF · 24 pages'},
      {title: 'DG32-2DOM preliminary datasheet', note: 'DG32-LITE plus the INT8 attention accelerator on a second clock.', href: url(DOCS + 'deepgrid-dg32-2dom-preliminary-datasheet.pdf'), meta: 'PDF · 12 pages'},
      {title: 'Architecture deck and narrated film', note: 'The same diagram walked through slide by slide.', href: url('/resources') + '?pkg=2dom', meta: 'Deck · film'},
    ],
    background: [
      {title: 'Clock domain crossing design and verification', note: 'Cummings, SNUG Boston 2008: two-flop synchronisers, handshakes with acknowledge feedback, and when a gray-pointer FIFO is needed instead.', href: 'https://www.paradigm-works.com/technical-library?term=clock+domain+crossing', meta: 'Paradigm Works library'},
      {title: 'Attention is all you need', note: 'Vaswani et al., 2017: the scaled dot-product attention the engine computes, QKᵀ then softmax then a weighted sum of values.', href: 'https://arxiv.org/abs/1706.03762', meta: 'arXiv'},
      {title: 'Quantization for integer-arithmetic-only inference', note: 'Jacob et al., 2018: the INT8 quantise and requantise scheme that integer engines follow.', href: 'https://arxiv.org/abs/1712.05877', meta: 'arXiv'},
      AMBA,
    ],
  },
  d100: {
    guide: D100_GUIDE,
    zones: [
      {name: 'Flight control', section: 'Component: Flight control',
        what: 'A lockstep DGridRiscV pair, shared with SKU-4 and on a DO-254 certification path, runs the PX4 or ArduPilot loop. The IMU, magnetometer and barometer arrive over three SPI links; motor commands leave as DShot600 on eight channels.'},
      {name: 'Visual-inertial odometry', section: 'Component: Visual-inertial odometry',
        what: 'Camera input enters over two-lane MIPI CSI-2 at up to 1080p60, passes the ISP and a FAST and BRIEF feature extractor, and the pose engine fuses it with the IMU into a 30 Hz six-degree-of-freedom pose.',
        why: 'The odometry is geometry, not learned perception, so estimating a pose needs neither GPS nor a trained model.'},
      {name: 'AI, phase 2', section: 'Component: AI accelerator (variant 2)',
        what: 'An INT8 and INT4 NPU of about 10 TOPS class, with 2 MB of SRAM, runs object detection and segmentation for obstacle avoidance, with attention and softmax in hardware at about 70% less power than a general AI accelerator. It is part of the 28 nm chip.',
        why: 'Vision AI needs dense logic that 130 nm cannot supply, so it is a separate die the flight functions never depend on.'},
      {name: 'AXI4 crossbar', section: 'Architecture Overview',
        what: 'A 128-bit crossbar joins the flight cores, the pose engine, the NPU and the platform blocks.'},
      {name: 'Failsafe island', section: 'Component: Failsafe island',
        what: 'A link monitor detects RC loss, GPS loss and IMU fault in hardware. It trips a safe-state machine that chooses return to home or land, and an independent path drives the ESCs directly.',
        why: 'Recovery has to work when the flight software is what failed, so it runs on isolated power and clock and bypasses the flight cores, the odometry and the AI.'},
      {name: 'Platform', section: 'Component: Platform',
        what: '2 GB of LPDDR4, eMMC or NAND for logging, a five-domain PMU, secure boot, Ethernet and USB3 for payload and ground link, CAN-FD, SPI and I²C for gimbal and payload, and JTAG.'},
      {name: 'Prototype and product strip', section: 'Prototype and product',
        what: 'An Artix-7 FPGA at 81.25 MHz validates the position engine; the product is a 28 nm chip, with the failsafe island buildable at 130 nm. FPGA timing closure is a prototype milestone, not a measurement of silicon.'},
    ],
    markers: [
      {mark: '①', text: 'The IMU, magnetometer, barometer and RC link reach the flight cores.'},
      {mark: '②', text: 'The cameras run through the ISP and the feature extractor to the pose engine.'},
      {mark: '③', text: 'The 30 Hz pose reaches the flight loop over the crossbar.'},
      {mark: '④', text: 'In normal flight, motor commands leave on ESC OUT.'},
      {mark: '⑤', text: 'The link monitor trips the safe-state machine on RC loss, GPS loss or an IMU fault.'},
      {mark: 'F', text: 'The independent path takes the ESCs directly, without the flight computer.'},
    ],
    primary: [
      {title: 'D100 architecture guide', note: 'Every block group, both data flows, prototype versus product, and what the architecture does not establish.', href: readHref(D100_GUIDE), meta: 'Opens in the site'},
      {title: 'SKU Blueprint, October 2026', note: 'D100: what it replaces, who uses it, its status and its architecture diagram.', href: url(DOCS + 'deepgrid-sku-blueprint-oct2026.pdf'), meta: 'PDF · 46 pages'},
    ],
    background: [
      {title: 'A Multi-State Constraint Kalman Filter for vision-aided inertial navigation', note: 'Mourikis and Roumeliotis, ICRA 2007: the EKF over a sliding window of camera poses that visual-inertial pose engines build on.', href: 'https://www-users.cse.umn.edu/~stergios/papers/ICRA07-MSCKF.pdf', meta: 'University of Minnesota · PDF'},
      {title: 'Machine learning for high-speed corner detection', note: 'Rosten and Drummond, ECCV 2006: the FAST corner detector.', href: 'https://doi.org/10.1007/11744023_34', meta: 'Springer · DOI'},
      {title: 'BRIEF: Binary Robust Independent Elementary Features', note: 'Calonder et al., ECCV 2010: the binary descriptor paired with FAST.', href: 'https://doi.org/10.1007/978-3-642-15561-1_56', meta: 'Springer · DOI'},
      {title: 'PX4 autopilot user guide', note: 'One of the two open flight stacks the flight cores run.', href: 'https://docs.px4.io/main/en/', meta: 'PX4 · Dronecode'},
      {title: 'ArduPilot Copter documentation', note: 'The other open flight stack the flight cores run.', href: 'https://ardupilot.org/copter/', meta: 'ArduPilot'},
      {title: 'MIPI CSI-2 specification overview', note: 'The camera interface the video arrives on.', href: 'https://www.mipi.org/specifications/csi-2', meta: 'MIPI Alliance'},
      DSHOT,
      AMBA,
    ],
  }
};

/** The architecture diagram each product page shows, keyed by product id. SKU-4 shows DG32-LITE because
 *  DG32-LITE is the implemented SKU-4 part; `note` says so on the page. The other SKUs are redrawn from
 *  their specs by scripts/sku-diagrams/ into sku-diagram-notes.ts. */
export type ProductDiagram = {notes: DiagramNotes; src: string; title: string; alt: string; width: number; height: number; drawio: string; guide: string; caption: string; note?: string;
};
export const productDiagrams: Partial<Record<string, ProductDiagram>> = {
  ...skuDiagrams,
  d100: {
    notes: diagramNotes.d100, src: '/diagrams/d100-architecture.svg', title: 'D100 system architecture', width: 1553, height: 945,
    drawio: '/downloads/d100-architecture.drawio', guide: D100_GUIDE,
    alt: 'D100 system architecture diagram: flight control, visual-inertial odometry and a variant-2 AI die on a 128-bit AXI4 crossbar, the platform blocks, and a failsafe island with its own path to the ESCs',
    caption: 'Architecture from the SKU Blueprint, October 2026: a 28 nm chip with a failsafe island buildable at 130 nm. Numbered markers trace normal flight; F marks the failsafe path to the ESCs. The dashed zone is the phase-2 AI accelerator.',
  },
  sku4: {
    notes: diagramNotes.lite, src: '/diagrams/dg32-lite-architecture.svg', title: 'DG32-LITE system architecture', width: 1518, height: 1045,
    drawio: '/downloads/dg32-lite-architecture.drawio', guide: LITE_GUIDE,
    alt: 'DG32-LITE system architecture diagram: safety core, memory and boot, supervision, on-chip bus, motor drive, sensing and math, connectivity and test, with the numbered current-control loop and the hardware fault path',
    caption: 'Numbered markers trace one current-control loop; F marks the fault latch, whose FAULT_N trips the gate driver in hardware.',
    note: 'DG32-LITE is the implemented SKU-4 part, so this is its diagram: 50 MHz, boot from ROM, no on-die flash. The specification below states the SKU-4 family targets, which go beyond it.',
  },
};
