'use client';
import {ArrowUpRight} from 'lucide-react';
import ProductTiles from './product-tiles';
import {PortfolioFinder} from './portfolio-finder';
import {DeepGridVisual} from './deepgrid-visual';
import {url} from './routes';
import {readHref} from './doc-links';
import {Workbench,SafetyWorkbench} from './portfolio-workbench';
import {EvaluationMatrix,ReuseMap,QualificationRoute,RoadmapRegister} from './portfolio-story';
import {claims} from './claims';
import {PortfolioV6Style} from './portfolio-v6-style';
const src=(s:string,section?:string)=>readHref('/downloads/'+s.replace(/^\/?downloads\//,''),section);
export function Overview({reduced}:{reduced:boolean}){return <div className="v6-home v11-home"><PortfolioV6Style/>
<section className="v11-hero" aria-labelledby="home-title"><div className="v11-hero-copy"><h1 id="home-title">Silicon for the<br/>physical world.</h1><p>From the motor that moves to the circuit that protects. DeepGrid brings control, power, sensing and interfaces into a system-first silicon portfolio.</p><div className="v11-actions"><a className="v11-button" href="#portfolio">Find your silicon <ArrowUpRight size={18}/></a><a className="v11-text-link" href="#dg32-proof">Inside DG32 <ArrowUpRight size={18}/></a></div><div className="v11-evidence-note"><span>Architecture to evaluation</span><p>Pre-silicon portfolio. Design targets and engineering evidence, clearly distinguished.</p></div></div><DeepGridVisual kind="overview" priority/></section>
<nav className="v11-application-strip" aria-label="Explore by application"><span>What are you building?</span>{[['Motors & drives','motors'],['Vehicles','vehicles'],['Defence & drones','defence'],['Grid & metering','grid'],['Board infrastructure','boards']].map(([name,path])=><a key={path} href={url('/use-cases/'+path)}>{name}<ArrowUpRight size={16}/></a>)}</nav>
<PortfolioFinder/>
<section className="v11-system"><div className="v11-system-intro"><h2>See where the<br/>silicon belongs.</h2><p>Select a function to locate its role in the system. The controller, power stage and interfaces each have a different job.</p><a className="v11-text-link" href={url('/applications')}>Explore system applications <ArrowUpRight size={18}/></a><DeepGridVisual kind="products"/></div><Workbench reduced={reduced}/></section>
<section className="v11-film-library"><details><summary>Explore all ten product films and design targets</summary><ProductTiles/></details></section>
<section className="v6-section v6-bone"><header><h2>Reuse the foundation.<br/>Keep specialist blocks specialist.</h2><p>Shared digital IP creates a foundation. Voltage, signal quality, RF behaviour and packaging still need their own engineering. The strategy extends through equipment makers into boxes, LRUs and assemblies.</p></header><ReuseMap/><a className="v6-link" href={url('/company')}>How the foundation is shared, and how it reaches equipment makers ↗</a> <a className="v6-cite" href={src('deepgrid-sku-compendium-architecture.md','3.5 Sheet 13: Organic Substrate Multi-Die SiP Packaging')}>Annex v3, Sheet 13</a></section>
<section className="v6-section" id="dg32-proof"><header><h2>DG32 makes the safety<br/>argument inspectable.</h2><p>MAIN executes. CHECKER follows two cycles behind. A result mismatch is recorded by a sticky fault latch; FAULT_N disables the gate driver through the hardware path.</p></header><SafetyWorkbench reduced={reduced}/><div className="v6-proof"><strong>{claims['fault-39'].figure}</strong><div><b>Injected-fault response · simulated</b><p>The complete reported path differs from the checker’s two-cycle execution skew. Hardware lockstep is a mechanism, not a functional-safety certificate.</p><a href={src(claims['fault-39'].source)}>Read the fault-path source ↗</a></div></div><a className="v6-link" href={url('/technology/safety')}>Inspect fault causes and reset behaviour ↗</a></section>
<section className="v6-section v6-diagnostics"><header><h2>Spend the remaining cycles<br/>on useful diagnosis.</h2><p>Hardware acquires, transforms and updates PWM. Firmware still runs the d/q PI regulators. Diagnostic workloads must fit the loop, memory and captured signal.</p></header><div className="v6-budget"><div><strong>177</strong><span>cycles · ADC acquisition</span></div><div><strong>53–58</strong><span>cycles · CORDIC</span></div><div><strong>≈300</strong><span>cycles · hardware datapath</span></div><div><strong>82%</strong><span>headroom at 10 kHz</span></div></div><div className="v6-roadmaps"><article><h3>The signal sets the diagnostic limit.</h3><p>The 8-bit ADC can limit feature quality. Some applications need conditioning or external conversion. Headroom at 10 kHz is not headroom at the simulated ≈100 kHz loop ceiling.</p></article><article><h3>2DOM adds a separate attention domain.</h3><p>An INT8 attention engine operates across a clock-domain boundary. It does not raise the control-loop ceiling or replace the hardware safety path.</p></article></div><a className="v6-link" href={url('/technology/control-loop')}>Inspect the hardware / firmware time budget ↗</a><a className="v6-link" href={url('/applications')}>Which diagnostic tasks fit the remaining cycles ↗</a> <a className="v6-cite" href={src('deepgrid-dg32-ai-architecture.md')}>Source: DG32 AI architecture</a></section>
<section className="v6-section v6-bone"><header><h2>A tapeout is a milestone.<br/>Qualification is another job.</h2><p>Architecture, simulation, returned silicon and qualified production answer different questions. Each development gate needs its own evidence.</p></header><QualificationRoute/><div className="v6-proof"><strong>198 days</strong><div><b>Analytic planning model · 30 digital + 168 physical days</b><p>This is a development model, not a demonstrated universal turnaround. Analog and high-voltage blocks can require additional silicon cycles.</p><a href={src('deepgrid-mature-silicon-architecture.md')}>Read the model and assumptions ↗</a></div></div><a className="v6-link" href={url('/evidence')}>Review published evidence and withheld claims ↗</a></section>
<section className="v6-section"><header><h2>Two roadmaps.<br/>Four reasons to change course.</h2><p>Process scaling and manufacturing diversification are separate decisions. The strategy names conditions that should delay, redirect or stop a programme.</p></header><RoadmapRegister/></section>
<section className="v6-section v6-close"><header><h2>Bring the system.<br/>Start with the evidence.</h2><p>Tell us the platform, voltage and power environment, control or sensing requirements, qualification needs and project timing. Start with the relevant architecture and the evidence still needed.</p></header><EvaluationMatrix/><div className="v6-actions"><a className="v6-primary" href={url('/contact')}>Discuss a system <ArrowUpRight size={18}/></a><a className="v6-link" href={url('/resources/docs')}>Open the engineering library ↗</a><a className="v6-link" href={url('/ask')}>Search the indexed documents ↗</a></div></section>
</div>}


