'use client';
import {url,type RouteId} from './routes';
import {ArrowUpRight} from 'lucide-react';
import {readHref} from './doc-links';
import './route-journey.css';
type Brief=[string,string,string[],string,string];
const briefs:Partial<Record<RouteId,Brief>>={
sku1:['Check the drive before the controller','A motor controller is chosen by the power stage it must drive and the loop it must close.',['State bus voltage, phase current and switching frequency.','Name the position sensor: Hall, quadrature encoder or sensorless.','Decide whether an independent safety supervisor is required beside it.'],'docs/deepgrid-sku-compendium-architecture.md','/products/sku-4'],
sku2:['Start from the accuracy class','A meter is judged on accuracy, tamper resistance and what it keeps through an outage.',['State the accuracy class and current range the meter must hold.','List the tamper events that must be detected and logged.','Name the backup source and how long the clock must run on it.'],'docs/deepgrid-sku-compendium-architecture.md','/use-cases/grid'],
sku3:['Start from the bus, not the rails','The input transient sets the power IC; the rails follow from the board.',['State the bus standard, surge and spike levels the input must survive.','List each rail with its current and its place in the start-up order.','Name the screening or qualification flow the box must pass.'],'docs/deepgrid-sku-compendium-architecture.md','/products/sku-6'],
sku4:['Separate detection from the response','Lockstep detects a wrong value; the board decides what happens next.',['Wire FAULT_N to the gate-driver enable and confirm the safe state.','Budget the control loop against the ~300 hardware cycles per iteration.','Check the ADC, memory and interface limits against the application.'],'dg32-lite-architecture-guide.md','/technology/safety'],
sku5:['Pair rate with reach','A transceiver is specified by the bus it lives on, not by its headline bit rate.',['State the protocol, node count and cable length together.','Give the common-mode range and the fault voltages the pins can see.','Name the ESD test and level, against its own standard.'],'docs/deepgrid-sku-compendium-architecture.md','/products/sku-9'],
sku6:['Set thresholds from the rails it watches','A supervisor is right when it ignores noise and catches every real dip.',['List each rail, its threshold and the tolerance it needs.','State the longest glitch to ignore and the shortest fault to catch.','Decide the watchdog window and what the reset must hold in reset.'],'docs/deepgrid-sku-compendium-architecture.md','/products/sku-3'],
sku7:['Start from the scene, then the waveform','Radar requirements come from what must be seen, how far and how fast.',['State range, resolution and the number of targets to track.','Name the mounting and the radios it must coexist with.','Plan for silicon validation: the RF front end has no FPGA stand-in.'],'docs/deepgrid-sku-compendium-architecture.md','/use-cases/vehicles'],
sku8:['Start from the panel and the cockpit','A display driver is fixed by the panel it drives and the light it is read in.',['State panel resolution, interface and column voltage.','Give the temperature and ambient-light range for contrast.','Decide how a frozen frame must be detected and reported.'],'docs/deepgrid-sku-compendium-architecture.md','/use-cases/defence'],
sku9:['Draw the zone before the chip','A zonal controller is sized by the loads and messages inside one zone.',['List the loads, their currents and protection needs.','Name the networks and the latency each critical message needs.','Separate safety, security and comfort functions on the bus.'],'docs/deepgrid-sdv-architecture.md','/use-cases/vehicles'],
sku10:['Start from the boot chain','A secure MCU is judged on what it refuses to run and where its keys live.',['State the firmware-signing scheme and who holds the signing key.','Name the secrets the device must keep and how rollback is prevented.','List the buses and pins the board needs from the 44 signal pins.'],'docs/deepgrid-sku-blueprint-oct2026.md','/use-cases/boards'],
sku11:['Start from the pack','A BMS controller is sized by the pack, its front end and the protection it must hold without software.',['State the cell count, chemistry and the front end already chosen.','List the trips that must act with the processor halted.','Say whether state-of-health data must feed a Battery Passport.'],'docs/deepgrid-sku-blueprint-oct2026.md','/use-cases/vehicles'],
d100:['Define the safe state first','A drone controller is judged on what happens when its flight computer fails.',['State the safe-state behaviour on link loss, GPS denial or a hang.','Name the sensors and the navigation accuracy required without GPS.','Decide what runs on 130 nm and what needs the 28 nm accelerator.'],'docs/deepgrid-d100-architecture.md','/use-cases/defence'],
read:['Read the conditions, not only the figure','A source document states each number with its method and its limits.',['Note whether a figure is a target, a simulation or a measurement.','Check the revision and the section the site cites.','Compare it with how /evidence grades the same claim.'],'docs/deepgrid-mature-silicon-architecture.md','/evidence'],
products:['From a function to a named part','Portfolio architectures and DG32 variants answer different selection questions.',['Identify the voltage, acquisition or interface job.','DG32 is SKU-4 safety MCU; it is distinct from SKU-1 motor power architecture.','Architecture breadth does not imply production availability.'],'deepgrid-sku-compendium-architecture.md','/applications'],
technology:['Follow the data and the fault','A functional diagram is useful when it explains who acts, what crosses a boundary and what can fail.',['Trace acquired data through ADC, CORDIC, software PI and PWM.','MAIN and CHECKER compare delayed committed results.','2DOM attention crosses a separate clock domain; control remains bounded.'],'dg32-lite-architecture-guide.md','/technology/control-loop'],
safety:['Distinguish detection from the complete response','Two-cycle checker skew and the reported 39-cycle fault response are different quantities.',['Comparator mismatch records a sticky first cause.','FAULT_N must connect to the external driver-disable path.','Reset and injection behaviour require validation; lockstep is not certification.'],'dg32-lite-architecture-guide.md','/evidence'],
control:['Budget the entire loop','The hardware datapath is only part of a current-control iteration.',['ADC acquisition: 177 cycles; CORDIC: 53–58 cycles.','d/q PI regulators run in firmware.','82% diagnostic headroom belongs to 10 kHz operation, not the ≈100 kHz ceiling.'],'dg32-lite-architecture-guide.md','/applications'],
die:['Separate layout evidence from functional geometry','A die view explains physical organisation; an illustrative cutaway cannot establish manufactured silicon.',['Check the implementation record and its revision.','Relate placement and routing to timing, clocks and power.','Post-route estimates need characterisation before becoming measured limits.'],'dg32-lite-architecture-guide.md','/evidence'],
package:['The board sees pins and electrical limits','The QFN-64 interface is where design assumptions become board requirements.',['DG32 package scope: 9 × 9 mm QFN-64.','Check 1.8 V core / 3.3 V I/O requirements against the source.','Pin-map confirmation, thermal behaviour and electrical limits require characterisation.'],'dg32-lite-architecture-guide.md','/contact'],
applications:['Start at the system, then inspect the workload','The indexed playbook maps tasks to signals, rates and implementation limits.',['Separate an application concept from a tested deployment.','A classifier needs usable signal quality, memory and cycle budget.','An advisory diagnosis does not replace the hardware fault path.'],'deepgrid-dg32-ai-architecture.md','/products'],
'uc-motors':['A drive is more than its controller','Motion puts the power stage, feedback, control loop and shutdown path in one engineering decision.',['SKU-1 addresses the motor-drive architecture; DG32 provides checked control.','Specify bus voltage, phase current, sensor topology and loop rate.','Validate driver-disable wiring and coast-down behaviour under a fault.'],'deepgrid-sku-compendium-architecture.md','/technology/safety'],
'uc-vehicles':['A vehicle harness shapes the silicon','Zonal integration depends on local loads, interfaces and system requirements.',['SKU-5 provides the physical interface architecture; SKU-9 the zonal scope.','DG SDV is a reference-platform architecture.','Transients, EMC and vehicle qualification remain application-specific evidence needs.'],'deepgrid-sdv-architecture.md','/products'],
'uc-defence':['Begin with the platform and its qualification route','Drone, avionics and defence use cases do not share one universal requirement.',['D100 supplies the drone architecture context.','State power, communications, environment and flight or mission constraints.','Treat screening, qualification and procurement eligibility as separate decisions.'],'deepgrid-d100-architecture.md','/company'],
'uc-grid':['Measurement quality decides the meter','Metering combines acquisition, calibration, power and deployment economics.',['SKU-2 is the meter architecture; PMIC and supervision are adjacent jobs.','Define accuracy, channels, isolation and calibration conditions.','An unsigned deployment commitment is a reason to delay the programme.'],'deepgrid-sku-compendium-architecture.md','/company'],
'uc-boards':['Predictable startup begins below firmware','Power management, reset supervision and interfaces support nearly every board.',['SKU-3 addresses rails and sequencing; SKU-6 addresses supervision.','Define supply ramp, brownout, reset and recovery requirements.','Check physical-layer voltage and harness constraints for SKU-5.'],'deepgrid-sku-compendium-architecture.md','/contact'],
evidence:['Ask what each result actually proves','Simulation, implementation and laboratory measurements answer different questions.',['Read the claim, method, conditions and revision together.','39 cycles is reported simulated fault response; it is not a measured silicon result.','Architecture and roadmap documents do not establish qualification or availability.'],'dg32-lite-architecture-guide.md','/procurement'],
procurement:['Turn a comparison into an evaluation plan','DG32’s claimed design advantages must be weighed against analog, memory and maturity gaps.',['Check current design requirements against the available source records.','Roadmap features are future scope, not present capability.','Ask for measured evidence before committing a production design.'],'dg32-lite-architecture-guide.md','/contact'],
resources:['Choose a document by the decision it supports','The library spans portfolio strategy, product architecture and workload analysis.',['Use the SKU compendium for function and part scope.','Use DG32 architecture for safety, timing and package details.','Use the AI workload analysis for signals, features and budget limits.'],'deepgrid-sku-compendium-architecture.md','/resources/docs'],
docs:['Read the source behind the figure','A deck or film helps explain; the named specification preserves conditions and caveats.',['Inspect document revision and evidence type.','Keep a latency or headroom figure attached to its operating conditions.','Resolve index shorthand against the corrective claim register and source.'],'dg32-lite-architecture-guide.md','/evidence'],
videos:['Use motion to understand a mechanism','Narrated architecture films illustrate causal paths and domain boundaries.',['A rendered mechanism is an explanation, not a laboratory observation.','Read captions and source documents alongside the animation.','Inspect loop timing and fault response as separate paths.'],'dg32-lite-architecture-guide.md','/technology'],
ask:['Search the index, then verify the source','Indexed retrieval makes the corpus navigable. It cannot independently validate its own assertions.',['Ask for a named product, mechanism or constraint.','Open the citation and check the surrounding conditions.','Treat graph links as discovery; source documents govern publication.'],'deepgrid-sku-compendium-architecture.md','/resources/docs'],
about:['A portfolio organised around physical jobs','The company story should lead to the engineering work and the evidence it needs.',['Motion, power, sensing, interfaces and safety form the portfolio.','Mature processes and reusable digital IP are methods, not proof of economics.','DG32 is the detailed pre-silicon proof point.'],'deepgrid-mature-silicon-architecture.md','/company'],
team:['Match the team to the engineering task','A biography supplies context; product evidence supplies the technical decision.',['Scope architecture, implementation and qualification responsibilities.','Review the source materials before defining an evaluation.','Discuss the system’s constraints with the team.'],'deepgrid-mature-silicon-architecture.md','/contact'],
recognition:['Separate recognition from product readiness','Awards and participation provide company context. They do not prove electrical performance.',['Review the stated programme or achievement in its own scope.','Do not transfer recognition to product certification.','Use the evidence register for design and implementation results.'],'dg32-lite-architecture-guide.md','/evidence'],
contact:['Bring the constraints that decide the part','A useful enquiry starts with a system requirement and a defined evidence gap.',['State the platform and silicon function, not only the chip name.','Include voltage, signal quality, interfaces, timing and environment.','Name qualification requirements and what must be measured before adoption.'],'deepgrid-sku-compendium-architecture.md','/products']};
/** Whether a route has an evaluation guide; Related renders the disclosure only then, so it never opens empty. */
export const hasBrief=(route:RouteId)=>Boolean(briefs[route]);
export function RouteJourney({route}:{route:RouteId}){const b=briefs[route];if(!b)return null;return <aside className="route-journey" aria-label="Engineering evaluation guide"><div><h2>{b[0]}</h2><p>{b[1]}</p></div><ol>{b[2].map((x,i)=><li key={x}><b>0{i+1}</b>{x}</li>)}</ol><nav aria-label="Evaluation next steps"><a href={readHref('/downloads/'+b[3])}>Read the relevant architecture <ArrowUpRight size={14} aria-hidden="true"/></a><a href={url(b[4])}>Continue the evaluation <ArrowUpRight size={14} aria-hidden="true"/></a></nav></aside>}
