import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.argv[2];if(!base)throw Error('Pass site base URL');
const chunk=JSON.parse(fs.readFileSync('app/data/graphrag-unified-index.json','utf8')).chunks.find(c=>c.id==='bp_track-b-d100-drone-soc-status');
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));let mode='success',requests=0;
await page.route('https://deepgrid-rerank.shekerkamma.workers.dev/answer',async route=>{
 if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':new URL(base).origin,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type'}});
 requests++;const body=route.request().postDataJSON();assert(body.question);assert(Array.isArray(body.sourceIds));assert(!body.sources);
 if(mode==='error')return route.fulfill({status:503,contentType:'application/json',headers:{'Access-Control-Allow-Origin':new URL(base).origin},body:JSON.stringify({error:'The model is unavailable. Please retry.'})});
 const claim={text:'The D100 has a separate planned funding round, dependent on mature-node revenue.',kind:'evidence',support:[{sourceId:chunk.id,quote:chunk.text.slice(0,100)}]};
 return route.fulfill({status:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':new URL(base).origin},body:JSON.stringify({model:'gemini-3.8-flash',sources:[chunk],answer:{answerable:true,title:'Separate planned funding',lead:claim,sections:[{heading:'Revenue comes first',paragraphs:[claim]}],gaps:[]}})});
});
await page.goto(base+'ask/',{waitUntil:'networkidle'});await page.locator('[data-ready="true"]').waitFor({state:'attached'});
const input=page.getByRole('searchbox',{name:'Search DeepGrid knowledge'});
assert.equal(await page.locator('.answer-essay').count(),0);
assert(!(await page.getByRole('button',{name:'Submit',exact:true}).isEnabled()));
await page.getByRole('button',{name:'The D100 funding decision',exact:true}).click();
await page.locator('[data-model="gemini-3.8-flash"]').waitFor({timeout:20000});
assert.equal(requests,1);assert.equal(await page.locator('.answer-essay h2').innerText(),await input.inputValue());
assert.equal(await page.locator('.answer-essay .executive-sources').getAttribute('open'),null);
await page.locator('.executive-ref').first().click();await page.locator('.answer-essay .executive-sources[open]').waitFor();
for(const link of await page.locator('.answer-essay .executive-sources a').all()){const href=await link.evaluate(a=>a.href);assert(href.startsWith(base));assert.equal((await page.request.get(href)).status(),200);}
mode='error';await input.fill('Explain the funding risk for a new investor');await input.press('Enter');
await page.getByRole('alert').waitFor({timeout:20000});assert.equal(await page.locator('.dr-answer-lead').count(),0);
mode='success';await page.getByRole('button',{name:'Retry answer'}).click();await page.locator('[data-model="gemini-3.8-flash"]').waitFor({timeout:20000});
assert.equal(requests,3);assert.equal(await page.getByText('Your next decision',{exact:true}).count(),0);
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
assert.deepEqual(errors,[]);await browser.close();
console.log('PASS Ask UI contract: one request per submission, cited narrative, source links, explicit failure, retry and mobile width. Uses mocked transport; live synthesis is tested separately.');
