'use client';
import Related from '../related';
import {FoundationLedger,SdvPlatform} from '../portfolio-story';
import {Shell} from '../shell';
import {ReuseMap,QualificationRoute,RoadmapRegister} from '../portfolio-story';
import {url} from '../routes';
import {readHref} from '../doc-links';
import {PortfolioV6Style} from '../portfolio-v6-style';
export default function Page(){return <Shell route="company"><div className="v6-home v6-company"><PortfolioV6Style/><section className="v6-section"><header><h1>Build the silicon around the equipment.</h1><p>DeepGrid’s mature-node strategy connects motion, power, sensing, interfaces and safety to the needs of equipment makers. DG32 is the detailed pre-silicon engineering case; the wider portfolio remains a set of individually scoped architectures.</p></header><ReuseMap level={2}/><a className="v6-link" href={readHref('/downloads/deepgrid-mature-silicon-architecture.md')}>Read the strategy whitepaper ↗</a></section><section className="v6-section"><header><h2>What travels between products, and what does not.</h2><p>A shared processor, tools and verification flow make the second chip cheaper than the first. Voltage, noise, radio frequency and screening do not transfer: each socket sets its own physics, and those blocks are engineered for it.</p></header><FoundationLedger/></section><section className="v6-section"><header><h2>One reference platform. Twelve scoped products.</h2><p>DG SDV is the architecture the portfolio is drawn from: secure, safe, host and accelerator domains on one regulated interconnect. Each product takes the part of it its socket needs.</p></header><SdvPlatform/></section><section className="v6-section v6-bone"><header><h2>Silicon reaches the customer inside a system.</h2><p>The whitepaper’s “boxes, not chips” strategy works through equipment makers and their assemblies or LRUs. It is a proposed commercial route, not proof of contracted demand, legal procurement eligibility or qualified production.</p></header><div className="v6-roadmaps"><article><h3>Start with the OEM socket.</h3><p>Agree voltage, signal quality, interfaces, package, environmental conditions and qualification evidence. A reusable digital block cannot erase those physical constraints.</p></article><article><h3>Separate opportunity from commitment.</h3><p>Architecture breadth, forecasts and a possible procurement route are not customer orders. Evaluation needs named requirements and decision gates.</p></article></div></section><section className="v6-section"><header><h2>A development method with evidence gates.</h2><p>The 198-day model allocates 30 digital and 168 physical days. It is analytic planning; analogue and high-voltage programmes may need extra silicon cycles.</p></header><QualificationRoute/></section><section className="v6-section"><header><h2>Two roadmaps. Explicit stop rules.</h2></header><RoadmapRegister/></section><section className="v6-section v6-close"><h2>Discuss the system and the evidence it needs.</h2><div className="v6-actions"><a className="v6-primary" href={url('/contact')}>Begin an evaluation ↗</a><a className="v6-link" href={url('/about/team')}>Meet the team ↗</a></div></section><section className="v6-section"><Related route="company"/></section></div></Shell>}


